### ISSUE TITLE
XLA crashes in collective-permute-motion when running JAX program (without any collective permute) 

### ISSUE THREAD

**Issue by jaro-sevcik** [openxla/xla#10394]
The Jax program below segfaults on a machine with 8 V100 GPUs. When looking at the XLA dumps, the last dump is from before collective-permute-motion. The problem seems to be that the [FindMovableClusterAtBodyRoot]( https://github.com/openxla/xla/blob/36b3b135bb75dd292c420f65d20b8925a306e709/xla/service/spmd/collective_permute_motion.cc#L91) function returns a cluster with the `collective_permute` field being null. This later crashes [here](https://github.com/openxla/xla/blob/36b3b135bb75dd292c420f65d20b8925a306e709/xla/service/spmd/collective_permute_motion.cc#L246), where the code assumes that returned cluster has the field set.

```python
import jax
from jax import lax
from jax._src import test_util as jtu
import jax.numpy as jnp
from jax._src.sharding_impls import (NamedSharding, PositionalSharding,
                                     SingleDeviceSharding, GSPMDSharding,
                                     TransferToMemoryKind,
                                     common_devices_indices_map)
from jax.sharding import PartitionSpec as P
import math
import numpy as np

def test():
  mesh = jtu.create_global_mesh((2,), ("x",))
  shape = (256, 128)
  np_inp = np.arange(math.prod(shape), dtype=np.float32).reshape(shape)
  s = NamedSharding(mesh, P("x"))
  inp = jax.device_put(np_inp, s)

  def f(x):
    def g(ys, _):
      y, _ = ys
      w = jnp.sin(y)
      return (w, jnp.sum(w)), None
    _, scan_out = jax.lax.scan(g, (x, np.array(1, dtype=np.float32)), [np_inp])[0]
    return scan_out

  f = jax.jit(jax.grad(f))
  f(inp)  # doesn't crash
 
test()
```

**Comment by toli-y** [comment]
@jaro-sevcik thanks for submitting the issue. Do you see it on other GPUs besides V100?

**Comment by jaro-sevcik** [comment]
Just tried on 8xH100; it reproduces there, too. (Also, see the PR #10395 for proposed fix and a regression test.)
