### ISSUE TITLE
Incorrect boundary behaviour of `igamma`, `igammac`

### ISSUE THREAD

**Issue by lucascolley** [openxla/xla#11151]
x-ref https://github.com/google/jax/issues/20507#issuecomment-2032789770

```python
> import jax
> import scipy
> scipy.special.gammainc(0, 1)
array(1., dtype=float32)
> jax.scipy.special.gammainc(0, 1)
array(nan, dtype=float32)
> scipy.special.gammaincc(0, 0)
array(nan, dtype=float32)
> jax.scipy.special.gammaincc(0, 0)
array(1., dtype=float32)
```

@steppi:

> If $(a, x) \rightarrow (0, 1)$ then $\text{gammainc}(a, x) \rightarrow 1.0$.
> 
> But
> 
>  $$\lim_{(a, x)\rightarrow (0, 0)} \text{gammaincc}(a, x)$$
> 
>  depends on the order in which the limit is taken. Taking first $x \rightarrow 0$ and leaving $a > 0$ fixed, the limit tends to 1. Taking $a \rightarrow 0$ and leaving $x > 0$ fixed, the limit tends to zero.

@jakevdp:

> We could probably address this at the JAX level, but it would come at the cost of adding a couple select statements to every evaluation of `gammainc` or `gammaincc`, which currently lower directly to a single call to `lax.igamma` or `lax.igammac` respectively.
> 
> Better I think would be to update the XLA implementations of these functions, which would have to be done upstream in [openxla/xla](https://github.com/openxla/xla)

As per https://github.com/google/jax/issues/20507#issuecomment-2032743256, ~the problem arises from a historical mistake in cephes, which has been corrected in SciPy~ see https://github.com/openxla/xla/issues/11151#issuecomment-2032962772.

**Comment by lucascolley** [comment]
see https://github.com/scipy/scipy/commit/3af8448114dd4a2755d513edb5a2272a338dc483 for the SciPy fix

**Comment by steppi** [comment]
> As per [google/jax#20507 (comment)](https://github.com/google/jax/issues/20507#issuecomment-2032743256), the problem arises from a historical mistake in cephes, which has been corrected in SciPy.

To clarify, this isn't necessarily a mistake in cephes. I think it's more correct to say that in SciPy, the domains of these functions were extended to include these limiting cases.

**Comment by cheshire** [comment]
Thanks for the report ! It's not entirely clear to me whether an XLA fix is needed, or whether doing https://github.com/google/jax/issues/20507#issuecomment-2032811291 in JAX is sufficient?

**Comment by lucascolley** [comment]
It seemed like @jakevdp was more keen on a change in XLA, but maybe things have changed.

**Comment by jakevdp** [comment]
If the differences are a matter of convention, then the change should be made in the JAX wrappers. If they're a matter of correctness, then the change should be made in XLA. I was under the impression that this is a matter of correctness, not convention.

**Comment by cheshire** [comment]
As far as I can tell, there's no `igamma` HLO, to what is this lowered?

**Comment by jakevdp** [comment]
Ah, my mistake, it looks like the implementation for these is in JAX.

**Comment by hawkinsp** [comment]
But note the XLA implementation in the client libraries (https://github.com/openxla/xla/blob/208496a001e2b93d1ac38df05a7c5d89c7cc153d/xla/client/lib/math.h#L59), which is *not* used by JAX, presumably has the same bug.

**Comment by cheshire** [comment]
@hawkinsp I guess ideally should be a bug on TF then?
