### ISSUE TITLE
Is there any operation in XLA capable of reserving blank memory?

### ISSUE THREAD

**Issue by ApsarasX** [openxla/xla#11287]
I am in the process of integrating [Dao-AILab/flash-attention](https://github.com/Dao-AILab/flash-attention) into XLA as a custom-call.

However, this particular `flash_attn` custom-call requires temporary GPU memory during its execution. 

Utilizing `StreamExecutor::Allocate/Deallocate` to dynamically allocate and release memory during execution significantly impacts performance.

Therefore, I am seeking a way to statically allocate a segment of GPU memory specifically for this `flash_attn` custom call at compile time. Ideally, the allocated memory's lifecycle would be confined to the execution scope of this `flash_attn` custom-call instruction.

**Comment by cheshire** [comment]
A canonical way to do it is to use a "fake" secondary output (e.g. `(bf16[<output-size>], bf16[<workspace-size>])`), which will force the main XLA allocator to allocate this memory. We use the same for convolutions and for matmuls.

**Comment by cheshire** [comment]
Hope this answers your question, feel free to reopen.

Also for flash attention in particular, a usual way would be to use either Pallas or jax-triton kernel.
