### ISSUE TITLE
`PjRtCApiBuffer::AcquireExternalReference` does not support `WaitUntilBufferReadyOnStream`

### ISSUE THREAD

**Issue by jjwilke** [openxla/xla#11535]
When wrapping a stream executor client with the C API, the returned external reference from `PjRtCApiBuffer::AcquireExternalReference` does not wrap a stream executor external reference and does not currently support `WaitUntilBufferReadyOnStream`. This prevents calls to, e.g.:

```
dlt_2 = xla_client._xla.buffer_to_dlpack_managed_tensor(buffer, stream.ptr)
```

**Comment by jyingl3** [comment]
Work-in-progress PR: https://github.com/openxla/xla/pull/11629, https://github.com/google/jax/pull/20805

**Comment by jyingl3** [comment]
The PRs have been merged. Closed this issue.
