### ISSUE TITLE
XLA CollectiveOpsUtil does not include kReduceScatter

### ISSUE THREAD

**Issue by ptoulme-aws** [openxla/xla#11742]
When debugging the XLA while loop unroller channel id creation, we found that HloOpcode::kReduceScatter was not included as a collective to generate new channel id for. 

While loop unroller location: https://github.com/openxla/xla/blob/79d745f5873c0c93bcb43b25436c212da1f2b997/xla/service/while_loop_unroller.cc#L201

Collective ops util location: 
https://github.com/openxla/xla/blob/79d745f5873c0c93bcb43b25436c212da1f2b997/xla/service/collective_ops_utils.cc#L611

We have added kReduceScatter locally and it fixed our channel id issues. 

Questions: 
1. Why is kReduceScatter not listed in the list of collective operations to replace channel id with?
2. Can kReduceScatter be added to the list if this is a bug?

**Comment by akuegel** [comment]
Can you please check whether https://github.com/openxla/xla/commit/f584acb552dd396e55e59811ab7e6d5ca19650c2 fixes this issue?

**Comment by akuegel** [comment]
I think it is fixed, please let us know in case this is still a problem.
