### ISSUE TITLE
PJRT `CopyCpuBufferToLiteral` of JAX buffer taking too long 

### ISSUE THREAD

**Issue by jon-chuang** [openxla/xla#12452]
Takes on average 344ms for 625MB of data. This is a throughput of 1.82 GB/s. I was under the impression that a memcpy throughput should be in the 10s of GBs.

Same result for `dtype=jnp.float16`

The actual D2H transfer was 11ms (or 56GB/s, which is in the ballpark for the PCIE bandwidth between my host and accelerator). For larger buffer sizes I measured at the slowest 11 GBps H2D transfer.

Shows up on my `jax.profiler.trace` perfetto trace as `D2H Dispatch`. The backend used is `gpu`.

https://github.com/openxla/xla/blob/bcc802c310f03b6114df36057602216a7aec3d27/xla/pjrt/cpu/abstract_tfrt_cpu_buffer.cc#L447

This is supposed to just be a memcpy

https://github.com/openxla/xla/blob/0c5de1a520492a581d20ac219e8511ff023a7ff5/xla/pjrt/cpu/abstract_tfrt_cpu_buffer.cc#L100

NUMA node pinning did not help.

**Comment by cheshire** [comment]
If we're just calling `std::memcpy` I'm not sure what else can we do, @ezhulenev any ideas?

**Comment by jon-chuang** [comment]
I measured the memcpy performance and indeed it is at peak still <4GB/s. I was simply surprised that a memcpy can be so much slower than a H2D transfer.

**Comment by cheshire** [comment]
Naive question: what would happen if we divided the slab to copy and called multiple std::memcpy from multiple threads?

**Comment by jon-chuang** [comment]
Confirm this result on other machines.

All I can think is that if the kernel is marked as in-place, then it ought to be able to take ownership of the CPU memory and reuse it instead of doing memcpy. It really is the bottleneck for doing any h2d copy in JAX and that is surprising to me.

**Comment by ezhulenev** [comment]
Yes, we need 4-8 threads to saturate memory bandwidth, single threaded memcpy is not enough. I don't think anyone benchmarked it properly because it's called not very often in workloads people care about.

**Comment by jon-chuang** [comment]
Actually, I just realised that `xla.batched_device_put` is precisely the API that achieves zero copy. It's a shame it's not the default. See: https://github.com/google/jax/issues/16905

I think that more work needs to be done to make this known or to make zero copy the default behaviour

**Comment by jon-chuang** [comment]
Regardless, I still feel that the API should support zero copy and that the frontend (e.g. JAX) should be able to tell the runtime when the buffer will be immutable

Similar to
https://github.com/openxla/xla/blob/fd58925adee147d38c25a085354e15427a12d00a/xla/python/py_array.cc#L1128C9-L1128C18

**Comment by lengstrom** [comment]
I observe similar issues; is there a workaround? Transferring GPU -> CPU JAX caps at 2.7 GB/s on my machine (H100 PCIe) while a simple CUDA program (see code here https://github.com/google/jax/issues/16905#issuecomment-2132041231) achieves ~25GB/s.

**Comment by jon-chuang** [comment]
The work around is to use `device_put` to explicitly transfer the cpu buffers to device first.

But I think the lazy kernel input copy triggering memcpy is a footgun.

**Comment by lengstrom** [comment]
Am new to jax so apologies if I don't fully understand - how do you actually operationalize this in jax?
