### ISSUE TITLE
Wrong output from JAX test after onednn change

### ISSUE THREAD

**Issue by hawkinsp** [openxla/xla#13054]
One of our JAX users reported a miscompilation in the following program when run on CPU:

```
import jax
import jax.numpy as jnp

w = jnp.array([1., 2., 3.], dtype=jnp.float32)
# w = jnp.array([10., 10., 10.], dtype=jnp.float32)  # this works
# w = jnp.array([1e-3, 1e-2, 1e-1], dtype=jnp.float32)  # this does not work
dim = len(w)
x = jnp.ones((dim,))
ys = jnp.ones((10**6, dim))
# ys = jnp.ones((10**5, dim)) # this works

def fun(x, y):
  diff = y - x
  out = jnp.dot(diff, w)
  # The following line should have no effect on the output or the derivatives
  # of this function. Removing it solves the bug.
  out = out + jnp.dot(jnp.dot(diff, jnp.zeros((dim, dim))), diff)
  return out

def mean_fun(x):
  outs = jax.vmap(lambda yy: fun(x, yy))(ys)
  return jnp.mean(outs)

jitted_grad = jax.jit(jax.grad(mean_fun))(x)
grad = jax.grad(mean_fun)(x)
print(f'Difference grads: {grad-jitted_grad}')
print(f'All close: {jnp.sum(jnp.abs(grad-jitted_grad)) < 1e-3}')
# Difference grads: [ 0.        -1.0000002 -2.0000007]
# All close: False
```

If working correctly, it should print:
```
Difference grads: [0. 0. 0.]
All close: True
```

I bisected the problem to XLA commit:
https://github.com/openxla/xla/commit/0dc5563a97d6fa4584b85cb29b4bfcf289604f0b

@jmaksymc

HLO dumps from that commit (bad) and the immediately preceding commit (good): [dumps.tgz](https://github.com/openxla/xla/files/15437598/dumps.tgz)

We should either fix or revert that commit.

**Comment by mdfaijul** [comment]
@hawkinsp @penpornk Thanks for reporting this issue. We are working on it.

**Comment by mdfaijul** [comment]
@hawkinsp @penpornk A PR fixing the bug has been submitted (https://github.com/openxla/xla/pull/13301)

**Comment by penpornk** [comment]
PR https://github.com/openxla/xla/pull/13301 has been merged. I have verified that the latest XLA commit (https://github.com/openxla/xla/commit/7d12719859ad52e2554d41094a74a4ec9d5592e6) produced the expected output. (Using nightly jax, e.g., 0.4.29.dev20240603, because of the recent ducc fft removal from jaxlib.)
