### ISSUE TITLE
lowering stablehlo to ptx

### ISSUE THREAD

**Issue by sei-jgwohlbier** [openxla/xla#13175]
Hi, I'm interested in lowering stablehlo to ptx. According to this https://openxla.org/xla/tools I think I should be able to go from stablehlo to llvm to ptx using `hlo-opt`. However, no executable `hlo-opt` is built when building from source. I found what I imagine is the source file in `xla/xla/mlir_hlo/tools/mlir-hlo-opt` and a `CMakeLists.txt`, but I'm not sure how to build it within the context of `bazel`.

Thanks!

**Comment by sei-jgwohlbier** [comment]
I did not have it properly installed. Trying to install it now, but running into errors. If I can't fix the errors I'll open a new issue.

**Comment by cheshire** [comment]
1. You can build hlo-opt yourself with bazel, there's no cmake build, and the tool is completely different from the one in mlir_hlo.
2. Note that most things you can't lower fully to PTX: PTX is interspersed with library calls and runtime instrumentation.

**Comment by cheshire** [comment]
I guess it could work, but it would be quite fragile, with no backwards/forward compatibility guaranteed.

**Comment by sei-jgwohlbier** [comment]
Ok, thanks. I'm just trying for proof of principle.
