### ISSUE TITLE
ReduceScatterCreator - Misses One Pattern

### ISSUE THREAD

**Issue by ptoulme-aws** [openxla/xla#13307]
The xla::gpu::ReduceScatterCreator pass misses one small pattern. 

It misses the case where the constant pool is  slice size * num_replica groups up to full tensor size. 
Example: 
```
Constant pool: {0,0,0,0,...128,128,128,128...256,256,256}
```
Example pool generation: 
```
std::vector<int32_t> repeated_pool;
  repeated_pool.reserve(replica_ids_size * num_replica_groups);
 
  for (int32_t idx = 0; idx < replica_ids_size; ++idx) {
    for (size_t group_idx = 0; group_idx < num_replica_groups; ++group_idx) {
      repeated_pool.push_back(idx * sinfo.size);
    }
  }
  ```

**Comment by cheshire** [comment]
Thanks! Do you plan to provide a patch?

**Comment by golechwierowicz** [comment]
IIRC ReduceScatterCreator is simply matching RS using primitives from `collective_opt_utils.cc` and performs a rewrite.

https://github.com/openxla/xla/blob/11c780430cb418c873bde6bc4757438f9bd32d46/xla/service/collective_opt_utils.cc#L301

It provides a couple of configurable options, so it might be a case that we just need to fiddle with these.

Can you provide a small reproducer? Usually small HLO (written by hand, or generated via JAX) is the best.

**Comment by ptoulme-aws** [comment]
This must have been fixed. I see it now catching this pattern.
