### ISSUE TITLE
All Gather Combiner - Coalesces different dtypes

### ISSUE THREAD

**Issue by ptoulme-aws** [openxla/xla#13305]
The all gather combiner pass currently coalesces different dtypes of all gathers. This effectively creates a heterogenous dtype all gather. Not all hardware types support this, and this should be refactored into a config to enable or disable this. 

https://github.com/openxla/xla/blob/4d355f39c068900ee92d98e30990d739ab1ea930/xla/service/all_gather_combiner.cc#L164

**Comment by cheshire** [comment]
> Not all hardware types support this

Sorry for the naive question, but since all-gather is just moving bits around, does dtype make a difference? Like, could we just effectively pretend it's a sequence of bytes regardless of the actual dtype?

**Comment by ptoulme-aws** [comment]
This still would require support downstream in the hardware specific compiler/runtime, which not all hardware has. I can submit a PR to add dtype as a key to the struct if user specifies do not coalesce different dtypes? Default will still be coalesce different dtypes together.

**Comment by ptoulme-aws** [comment]
> > Not all hardware types support this
> 
> Sorry for the naive question, but since all-gather is just moving bits around, does dtype make a difference? Like, could we just effectively pretend it's a sequence of bytes regardless of the actual dtype?

It is not that simple when programming the hardware. I have made a PR that allows users to specify this. Default is true to maintain existing behavior. Please review.
