### ISSUE TITLE
[XLA:GPU] cuDNN norm rewriter fails with OOB shape access

### ISSUE THREAD

**Issue by bchetioui** [openxla/xla#13361]
When ran in debug mode, `CudnnNormRewriterTest.LayerNorm4D12Degenerate2` and `CudnnNormRewriterTest.LayerNormTrain4D12Degenerate2` and `CudnnNormRewriterTest.LayerNormTrainBackward4D12Degenerate2` break with (truncated) stack trace

```
F0604 00:55:39.798943    9238 logging.cc:58] assert.h assertion failed at absl/container/inlined_vector.h:377 in auto absl::InlinedVector<long, 6>::operator[](size_type)::(anonymous class)::operator()() const [T = long, N = 6, A = std::allocator<long>]: false && "i < size()"
*** Check failure stack trace: ***
    ...
    @     0x7fcd6e6c5f6a  absl/container/inlined_vector.h:377 absl::InlinedVector<>::operator[]()::{lambda()#1}::operator()()
    @     0x7fcd6e6c5eeb  absl/container/inlined_vector.h:377 absl::InlinedVector<>::operator[]()
    @     0x7fcd6e6c5bda  tensorflow/compiler/xla/shape.h:170 xla::Shape::dimensions()
    @     0x7fcd507e97f5  tensorflow/compiler/xla/service/gpu/cudnn_norm_rewriter.cc:975 xla::gpu::(anonymous namespace)::CudnnNormRewriterVisitor::MatchLayerNorm()
```

denoting seemingly an OOB shape access.

**Comment by bchetioui** [comment]
@philipphack I ran this with `-DUNDEBUG`---did you set this?

I don't have an OSS command on hand, sorry. If that doesn't work, I can try to figure one out.

**Comment by philipphack** [comment]
It would be helpful if you can share a bazel command that reproduces the issue.

**Comment by bchetioui** [comment]
`bazel test --compilation_mode=opt --copt=-UNDEBUG /path/to/test` should be the equivalent of the internal command I ran. (Note that at HEAD, I disabled the broken tests now, so you will have to remove the `GTEST_SKIP()`s there to reproduce.)

**Comment by philipphack** [comment]
Thanks. The shape comparison seems to be redundant. Removed in #13392.
