### ISSUE TITLE
How to use PJRT C API v.2

### ISSUE THREAD

**Issue by janpfeifer** [openxla/xla#13733]
hi, I'm forking the previous #7038 because that seems to get PJRT to work leveraging the C++ wrappers.

I'm trying to build a [PJRT wrap for Go](https://github.com/gomlx/gopjrt) leveraging purely the [PJRT C API](https://github.com/openxla/xla/blob/main/xla/pjrt/c/pjrt_c_api.h) to power an [ML framework for Go](https://github.com/gomlx/gomlx) (I've written here before so some may be familiar with the project. But hopefully the questions are generic for anyone building an ML for any X language (or anyone else needing compiled accelerator code).

**Question 1** and the most important (before I spend too much time on it): is using simply the `pjrt_c_api.h` file, doing a `dlopen` on the compiled plugins (from `openxla/xla` for now), and using it directly a valid approach ? Or does one need any of the helper/wrappers around it under `xla/xla/pjrt` ?  Are there specific considerations or limitations one should be aware of when taking this path?

For the time being in the GoMLX project I'll use XlaBuilder to generate the StableHLO (it provides me shape inference of the result of the ops). But later the goal would be to use purely the PJRT C API, if viable.

**Question 2**: While the pjrt_c_api.h header provides function definitions, there are several aspects that I found unclear and I was wondering if there is additional documentation. Some examples -- apologies if noob questions, but I usually don't interact at this level:

1. What are the available extension types and their purpose ?
2. Are there documentation on the CPU/GPU plugins (from OpenXLA/XLA repository) ?
3. Client/Multi-Node Semantics: How are PjRT clients and multi-node setups related? If there are multiple GPUs on a machine, should one client be created per GPU instance? Is this behavior consistent across different plugins?
4. Buffer Abstractions: What are the underlying abstractions for PjRT buffers? What synchronization mechanisms are in place (host-device, cross-device, cross-plugin)? How does the concept of tiling (mentioned in pjrt_c_api.h) work?
 
Are there any design documents or references (perhaps from JAX or TensorFlow) that would be helpful in understanding these aspects of the C API?
 
Btw, since I'm opening the issue, one potential (C vs C++) issue with `pjrt_c_api.h`: on [line 56](https://github.com/openxla/xla/blob/main/xla/pjrt/c/pjrt_c_api.h#L56) whenever I include it on the most trivial C file, the compile fails with:

```
./pjrt_c_api.h:56:3: error: unknown type name 'PJRT_Extension_Base'
```

Seems simple, it's missing a `struct` because `struct PJRT_Extension_Base` is not aliased with a typedef yet, it only happens 2 lines below. It does compile in C++ though. Maybe I'm missing some compilation flag  for C? (I tried both gcc and clang, both reported the same error).

```C
typedef struct PJRT_Extension_Base {
  size_t struct_size;
  PJRT_Extension_Type type;
  PJRT_Extension_Base* next;   // <-- line with error.
} PJRT_Extension_Base;
PJRT_DEFINE_STRUCT_TRAITS(PJRT_Extension_Base, next);
```

Thanks in advance for any answers and/or pointers! :)

ps.: If I manage to get the PJRT C API to work nicely, I would be happy to contribute with documentation (perhaps a tutorial) on how to use PJRT C API for consumers (as opposed to hardware developers) that is generic to help others.

**Comment by skye** [comment]
There's no documentation (beyond comments) for callers of PJRT unfortunately. We have a guide for _implementing_ the PJRT API and creating a JAX plugin (https://github.com/openxla/xla/blob/main/docs/pjrt_integration.md), but not for using it. Contributions welcome :)

> is using simply the pjrt_c_api.h file, doing a dlopen on the compiled plugins (from openxla/xla for now), and using it directly a valid approach ?

Yes! JAX uses the C++ wrapper (https://github.com/openxla/xla/blob/main/xla/pjrt/pjrt_c_api_client.h) because it's convenient for us, but it's totally fine to call the C API directly, e.g. if you don't wanna deal with the C++ build.

All plugins should implement a `GetPjrtApi` method that returns a `PJRT_Api*`, which is the endpoint for all PJRT functionality. So you can do something like this: https://github.com/openxla/xla/blob/04deefca530e71080d5dd594afc3465540558def/xla/pjrt/pjrt_api.cc#L95-L101

> What are the available extension types and their purpose ?

Available extensions: https://github.com/openxla/xla/blob/04deefca530e71080d5dd594afc3465540558def/xla/pjrt/c/pjrt_c_api.h#L42-L47
Look for corresponding extension headers in the same directory.

> Are there documentation on the CPU/GPU plugins (from OpenXLA/XLA repository) ?

No. We only publish a GPU plugin for now: https://pypi.org/project/jax-cuda12-pjrt/ (cuda11 also available)

> Client/Multi-Node Semantics: How are PjRT clients and multi-node setups related? If there are multiple GPUs on a machine, should one client be created per GPU instance? Is this behavior consistent across different plugins?

You can create one client per host, including for multi-GPU nodes. This is generally true across platforms. Multi-host is more complicated, I suggest starting with one host for now, and looking at the GPU C++ implementation for a multi-host example.

> Buffer Abstractions: What are the underlying abstractions for PjRT buffers? What synchronization mechanisms are in place (host-device, cross-device, cross-plugin)? How does the concept of tiling (mentioned in pjrt_c_api.h) work?

PJRT buffers are (mostly) immutable on-device buffers. I recommend reading the PJRT_Buffer API comments for semantics, you can file an issue if a specific thing is unclear. Cross-plugin anything is not supported. See https://openxla.org/xla/tiled_layout for what tiling means.

**Comment by skye** [comment]
> Seems simple, it's missing a struct because struct PJRT_Extension_Base is not aliased with a typedef yet, it only happens 2 lines below.

This is probably a mistake (I personally am not an expert C programmer...). Wanna open a PR?

> ps.: If I manage to get the PJRT C API to work nicely, I would be happy to contribute with documentation (perhaps a tutorial) on how to use PJRT C API for consumers (as opposed to hardware developers) that is generic to help others.

This would be awesome!

**Comment by janpfeifer** [comment]
Thank you so much for the links. I already tested the JAX cuda plugin with my initial implementation and it works perfectly.

Small PR fixing the C issue: #13819 

Playing with it I realized that PJRT doesnt' take StableHLO text as input ... so I'll need to link as well XlaComputation as well. Any considerations on this ?

**Comment by cheshire** [comment]
> Playing with it I realized that PJRT doesnt' take StableHLO text as input

I think it should? At least that's one of the options?

**Comment by janpfeifer** [comment]
Not that is documented in [`pjrt_c_api.h:546`](https://github.com/openxla/xla/blob/main/xla/pjrt/c/pjrt_c_api.h#L546).

Also looking at the [c++ example in the other thread](https://github.com/openxla/xla/issues/7038#issuecomment-1813393228), notice it converts the HLO text to whatever PJRT takes as input using both, `LoadFromModule` and `XlaCompilation`.

I'm still trying to figure out how to properly compile it properly in Bazel (some visibility issues), but I noticed that to compile that it includes the whole LLVM. 

That prompts another couple of questions:

**Question 1**: who needs LLVM to compile the StableHLO code ? Is LLVM included in the PJRT plugin, on the thing that compiles the text to the HloModule, or both ?

**Question 2**: what does `LoadFromModule` and `XlaCompilation` do to the StableHLO ?

**Comment by janpfeifer** [comment]
So, as an alternative path to a minimum example, and likely more what I need, I created what I thought would be a minimum "hello world" XlaBuilder program in c++, `min_xla_builder.cc`:

```cc
#include <iostream>
#include "xla/client/xla_builder.h"
#include "xla/client/xla_computation.h"

int main(int argc, char** argv)
{
    // Load HloModule from file.
    auto b = new xla::XlaBuilder("x^2");
    return 0;
}
```

I put this file inside the XLA repository, under `.../xla/my`, so I wouldn't need to figure out how to create a new Bazel project and link XLA -- somehow it keeps failing.

I also created the following trivial BUILD file:

```py
cc_binary(
    name = "min_xla_builder",
    srcs = ["min_xla_builder.cc"],
    deps = [
        "//xla/client:xla_computation",
        "//xla/client:xla_builder",
        "//xla:xla_data_proto_cc",
        "//xla:xla_proto_cc",
   ],
)
```

Then using a fresh `tensorflow/build` docker ([per instructions](https://github.com/openxla/xla/blob/main/docs/developer_guide.md)), I try to compile with:

```sh
$ ./configure.py --backend=CPU
$ bazel build my:min_xla_builder
(... normal compilation goes on for a while ...)
ERROR: /xla/xla/my/BUILD:1:10: Linking my/min_xla_builder failed: (Exit 1): clang failed: error executing command (from target //my:min_xla_builder) /usr/
lib/llvm-17/bin/clang @bazel-out/k8-opt/bin/my/min_xla_builder-2.params                                                                                   
ld.lld: error: undefined symbol: xla::OpMetadata::OpMetadata(google::protobuf::Arena*, bool)
>>> referenced by xla_builder.cc
>>>               bazel-out/k8-opt/bin/xla/client/_objs/xla_builder/xla_builder.o:(xla::XlaBuilder::XlaBuilder(std::__cxx11::basic_string<char, std::char_
traits<char>, std::allocator<char>> const&))

ld.lld: error: undefined symbol: xla::FrontendAttributes::FrontendAttributes(google::protobuf::Arena*, bool)
>>> referenced by xla_builder.cc
>>>               bazel-out/k8-opt/bin/xla/client/_objs/xla_builder/xla_builder.o:(xla::XlaBuilder::XlaBuilder(std::__cxx11::basic_string<char, std::char_
traits<char>, std::allocator<char>> const&))
>>> referenced by hlo_instruction.cc
>>>               bazel-out/k8-opt/bin/xla/hlo/ir/_objs/hlo/hlo_instruction.o:(_GLOBAL__sub_I_hlo_instruction.cc)

ld.lld: error: undefined symbol: xla::OpSharding::~OpSharding()
```

So Bazel compiles, but fails to link, all seem to be missing proto-generated related symbols.

Any ideas why ? What is the minimum needed to link to get XlaBuilder to work ? -- so far it didn't try to link LLVM, so that looks good.

Thanks!!

**Comment by janpfeifer** [comment]
Just as an update, I'm just releasing the v0.0.1 of [gopjrt](https://github.com/gomlx/gopjrt),  a Go wrapper for:

1. PJRT: it's even simple to run simple Jax functions (exported as HLO).
2. XlaBuilder: with a minimal linkage (my initial linkage used almost 500Mb, now it only takes 13Mb).

Even though this is a low-level API so to say (I'm aiming at using [GoMLX](https://github.com/gomlx/gomlx) to use it), it's simple enough for some straight use cases. E.g: a [Mandelbrot Set drawn using XlaBuilder+PJRT and benchmarks](https://github.com/gomlx/gopjrt/blob/main/examples/mandelbrot.ipynb)

THanks a ton @cheshire and @skye for the help!! Very appreaciated.
