### ISSUE TITLE
Compiling xla/stream_executor/gpu/gpu_timer_kernel_cuda.cu.cc [for tool] failed

### ISSUE THREAD

**Issue by huhuiqi7** [openxla/xla#13889]
environment:
cuda=12.2, nccl=2.19.3-1+cuda12.2, clang=17.0.2, python=3.9.19, Ubuntu=20.04

compile command:
`./configure.py --backend=CUDA --clang_path=/usr/bin/clang-17 --nccl`
`HERMETIC_PYTHON_VERSION=3.9 bazel build --repo_env=HERMETIC_PYTHON_VERSION --test_output=all --spawn_strategy=sandboxed //xla/... --python_path=/root/miniconda3/envs/py39/bin/python --sandbox_debug`

error compile log:
```
ERROR: /root/pythonlib/xla-mesha/xla/xla/stream_executor/gpu/BUILD:332:19: Compiling xla/stream_executor/gpu/gpu_timer_kernel_cuda.cu.cc [for tool] failed: (Exit 2): process-wrapper failed: error executing command 
  (cd /root/.cache/bazel/_bazel_root/0a980004a407129aa21471eabbf76fbe/sandbox/processwrapper-sandbox/5002/execroot/xla && \
  exec env - \
    LD_LIBRARY_PATH=/usr/local/cuda/lib64/:/usr/local/nvidia/lib:/usr/local/nvidia/lib64 \
    PATH=/usr/local/bin:/home/username/miniconda/bin:/root/miniconda3/envs/py39/bin:/root/miniconda3/condabin:/usr/local/cuda/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    PWD=/proc/self/cwd \
    TMPDIR=/root/tmp \
  /root/.cache/bazel/_bazel_root/install/20da5ab742b8d3d499c34fdafcd3c8b8/process-wrapper '--timeout=0' '--kill_delay=15' '--stats=/root/.cache/bazel/_bazel_root/0a980004a407129aa21471eabbf76fbe/sandbox/processwrapper-sandbox/5002/stats.out' external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF bazel-out/k8-opt-exec-50AE0418/bin/xla/stream_executor/gpu/_objs/gpu_timer_kernel_cuda/gpu_timer_kernel_cuda.cu.d '-frandom-seed=bazel-out/k8-opt-exec-50AE0418/bin/xla/stream_executor/gpu/_objs/gpu_timer_kernel_cuda/gpu_timer_kernel_cuda.cu.o' '-DEIGEN_MAX_ALIGN_BYTES=64' -DEIGEN_ALLOW_UNALIGNED_SCALARS '-DEIGEN_USE_AVX512_GEMM_KERNELS=0' -DHAVE_SYS_UIO_H -DTF_USE_SNAPPY '-DGOOGLE_CUDA=1' '-DBAZEL_CURRENT_REPOSITORY=""' -iquote . -iquote bazel-out/k8-opt-exec-50AE0418/bin -iquote external/tsl -iquote bazel-out/k8-opt-exec-50AE0418/bin/external/tsl -iquote external/eigen_archive -iquote bazel-out/k8-opt-exec-50AE0418/bin/external/eigen_archive -iquote external/ml_dtypes -iquote bazel-out/k8-opt-exec-50AE0418/bin/external/ml_dtypes -iquote external/com_google_absl -iquote bazel-out/k8-opt-exec-50AE0418/bin/external/com_google_absl -iquote external/nsync -iquote bazel-out/k8-opt-exec-50AE0418/bin/external/nsync -iquote external/local_config_cuda -iquote bazel-out/k8-opt-exec-50AE0418/bin/external/local_config_cuda -iquote external/com_google_protobuf -iquote bazel-out/k8-opt-exec-50AE0418/bin/external/com_google_protobuf -iquote external/snappy -iquote bazel-out/k8-opt-exec-50AE0418/bin/external/snappy -iquote external/double_conversion -iquote bazel-out/k8-opt-exec-50AE0418/bin/external/double_conversion -iquote external/com_googlesource_code_re2 -iquote bazel-out/k8-opt-exec-50AE0418/bin/external/com_googlesource_code_re2 -Ibazel-out/k8-opt-exec-50AE0418/bin/external/ml_dtypes/_virtual_includes/float8 -Ibazel-out/k8-opt-exec-50AE0418/bin/external/ml_dtypes/_virtual_includes/intn -Ibazel-out/k8-opt-exec-50AE0418/bin/external/local_config_cuda/cuda/_virtual_includes/cuda_headers_virtual -isystem external/eigen_archive -isystem bazel-out/k8-opt-exec-50AE0418/bin/external/eigen_archive -isystem external/eigen_archive/mkl_include -isystem bazel-out/k8-opt-exec-50AE0418/bin/external/eigen_archive/mkl_include -isystem external/ml_dtypes -isystem bazel-out/k8-opt-exec-50AE0418/bin/external/ml_dtypes -isystem external/ml_dtypes/ml_dtypes -isystem bazel-out/k8-opt-exec-50AE0418/bin/external/ml_dtypes/ml_dtypes -isystem external/nsync/public -isystem bazel-out/k8-opt-exec-50AE0418/bin/external/nsync/public -isystem external/local_config_cuda/cuda -isystem bazel-out/k8-opt-exec-50AE0418/bin/external/local_config_cuda/cuda -isystem external/local_config_cuda/cuda/cuda/include -isystem bazel-out/k8-opt-exec-50AE0418/bin/external/local_config_cuda/cuda/cuda/include -isystem external/com_google_protobuf/src -isystem bazel-out/k8-opt-exec-50AE0418/bin/external/com_google_protobuf/src -fmerge-all-constants -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -fPIE -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -fno-omit-frame-pointer -no-canonical-prefixes -DNDEBUG -g0 -O2 -ffunction-sections -fdata-sections '--cuda-path=/usr/local/cuda-12.2' -g0 -w -g0 '-std=c++17' -x cuda '-DGOOGLE_CUDA=1' '--no-cuda-include-ptx=all' '--cuda-include-ptx=sm_80' '--cuda-gpu-arch=sm_80' '-Xcuda-fatbinary=--compress-all' '-nvcc_options=expt-relaxed-constexpr' -c xla/stream_executor/gpu/gpu_timer_kernel_cuda.cu.cc -o bazel-out/k8-opt-exec-50AE0418/bin/xla/stream_executor/gpu/_objs/gpu_timer_kernel_cuda/gpu_timer_kernel_cuda.cu.o)
/usr/lib/llvm-17/lib/clang/17/include/emmintrin.h(47): error: identifier "__bf16" is undefined
  typedef __bf16 __v8bf __attribute__((__vector_size__(16), __aligned__(16)));
          ^

/usr/lib/llvm-17/lib/clang/17/include/emmintrin.h(48): error: identifier "__bf16" is undefined
  typedef __bf16 __m128bh __attribute__((__vector_size__(16), __aligned__(16)));
          ^

2 errors detected in the compilation of "xla/stream_executor/gpu/gpu_timer_kernel_cuda.cu.cc".
```

**Comment by beckerhe** [comment]
Can you check whether adding `--cuda-compiler=clang` to your `configure.py` call changes anything?

**Comment by huhuiqi7** [comment]
> Can you check whether adding `--cuda-compiler=clang` to your `configure.py` call changes anything?
Thanks! Now there is another error:
ERROR: /root/pythonlib/xla-mesha/xla/xla/hlo/experimental/auto_sharding/BUILD:300:14: Linking xla/hlo/experimental/auto_sharding/auto_sharding_runner failed: (Exit 1): process-wrapper failed: error executing command 
  (cd /root/.cache/bazel/_bazel_root/0a980004a407129aa21471eabbf76fbe/sandbox/processwrapper-sandbox/2585/execroot/xla && \
  exec env - \
    CLANG_COMPILER_PATH=/usr/lib/llvm-17/bin/clang \
    CLANG_CUDA_COMPILER_PATH=/usr/lib/llvm-17/bin/clang \
    CUDA_TOOLKIT_PATH=/usr/local/cuda-12.2 \
    DOCKER_CACHEBUSTER=1696724010850853839 \
    LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64 \
    PATH=/root/.cache/bazelisk/downloads/bazelbuild/bazel-6.5.0-linux-x86_64/bin:/root/miniconda3/envs/py39/bin:/root/miniconda3/bin:/root/miniconda3/condabin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/root/miniconda3/envs/py39/bin/python3 \
    TF2_BEHAVIOR=1 \
    TF_CUBLAS_VERSION=12.2.5 \
    TF_CUDA_CLANG=1 \
    TF_CUDA_COMPUTE_CAPABILITIES=8.0 \
    TF_CUDNN_VERSION=8 \
    TF_NCCL_VERSION=2.19.3 \
    TMPDIR=/tmp \
  /root/.cache/bazel/_bazel_root/install/20da5ab742b8d3d499c34fdafcd3c8b8/process-wrapper '--timeout=0' '--kill_delay=15' '--stats=/root/.cache/bazel/_bazel_root/0a980004a407129aa21471eabbf76fbe/sandbox/processwrapper-sandbox/2585/stats.out' /usr/lib/llvm-17/bin/clang @bazel-out/k8-opt/bin/xla/hlo/experimental/auto_sharding/auto_sharding_runner-2.params)
/usr/bin/ld: bazel-out/k8-opt/bin/xla/stream_executor/cuda/libcuda_platform_cuda_only.lo(cuda_platform.o): in function `stream_executor::gpu::CudaPlatform::~CudaPlatform()':
cuda_platform.cc:(.text._ZN15stream_executor3gpu12CudaPlatformD2Ev+0x18): undefined reference to `stream_executor::ExecutorCache::~ExecutorCache()'
/usr/bin/ld: bazel-out/k8-opt/bin/xla/stream_executor/cuda/libcuda_platform_cuda_only.lo(cuda_platform.o): in function `stream_executor::gpu::CudaPlatform::~CudaPlatform()':
cuda_platform.cc:(.text._ZN15stream_executor3gpu12CudaPlatformD0Ev+0x18): undefined reference to `stream_executor::ExecutorCache::~ExecutorCache()'
/usr/bin/ld: bazel-out/k8-opt/bin/xla/stream_executor/cuda/libcuda_platform_cuda_only.lo(cuda_platform.o): in function `stream_executor::gpu::CudaPlatform::GetExecutor(stream_executor::StreamExecutorConfig const&)':
cuda_platform.cc:(.text._ZN15stream_executor3gpu12CudaPlatform11GetExecutorERKNS_20StreamExecutorConfigE+0x1d): undefined reference to `stream_executor::ExecutorCache::Get(stream_executor::StreamExecutorConfig const&)'
/usr/bin/ld: cuda_platform.cc:(.text._ZN15stream_executor3gpu12CudaPlatform11GetExecutorERKNS_20StreamExecutorConfigE+0x49): undefined reference to `stream_executor::ExecutorCache::GetOrCreate(stream_executor::StreamExecutorConfig const&, std::function<absl::lts_20230802::StatusOr<std::unique_ptr<stream_executor::StreamExecutor, std::default_delete<stream_executor::StreamExecutor> > > ()> const&)'
/usr/bin/ld: bazel-out/k8-opt/bin/xla/stream_executor/cuda/libcuda_platform_cuda_only.lo(cuda_platform.o): in function `_GLOBAL__sub_I_cuda_platform.cc':
cuda_platform.cc:(.text.startup+0x6b): undefined reference to `stream_executor::ExecutorCache::ExecutorCache()'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Target //xla/hlo/experimental/auto_sharding:auto_sharding_runner failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 433.724s, Critical Path: 237.97s
INFO: 4451 processes: 1867 internal, 1 local, 2583 processwrapper-sandbox.
FAILED: Build did NOT complete successfully

**Comment by cheshire** [comment]
> Can you check whether adding --cuda-compiler=clang to your configure.py call changes anything?

@beckerhe  Isn't that the default?

**Comment by beckerhe** [comment]
No, it's NVCC according to https://github.com/openxla/xla/blob/55816f32719de2cf3b29d309ee7e0e33ca047431/build_tools/configure/configure.py#L465
