### ISSUE TITLE
ROCm CI build failed in all recent PRs

### ISSUE THREAD

**Issue by apivovarov** [openxla/xla#14084]
ROCm CI build failed in all recent PRs

**Comment by cheshire** [comment]
The AMD build is community maintained, I would ping @i-chaochen , @jayfurmanek and others.

**Comment by i-chaochen** [comment]
Hi @apivovarov @cheshire thanks for the ping.

the build is pending on this PR https://github.com/openxla/xla/pull/14017

**Comment by hsharsha** [comment]
ROCm CI fails due to #14014 . This is addressed in #14017
