### ISSUE TITLE
[CPU] dot(f16, f32) -> f16 - crashes on cpu. 

### ISSUE THREAD

**Issue by apivovarov** [openxla/xla#14607]
The following hlo fails to run on cpu

```c
  HloModule module

  ENTRY main {
    p0 = f16[2,16]{1,0} parameter(0)
    p1 = f32[16,2]{1,0} parameter(1)
    ROOT dot = f16[2,2]{1,0} dot(p0, p1),
        lhs_contracting_dims={1}, rhs_contracting_dims={0}
  }
```
command to run:
```bash
./bazel-bin/xla/tools/run_hlo_module --platform=CPU --print_literals=true \
--reference_platform="" a.hlo
```
Error:
```
Running HLO module with runner Host...
2024-07-08 22:07:59.856851: I xla/service/dump.cc:532] HloModule dump enabled with path prefix: , suffix: 0000.sharding-removal.after_pipeline-start.before_sharding-remover
2024-07-08 22:07:59.886253: E xla/status_macros.cc:56] INTERNAL: RET_CHECK failure (xla/service/cpu/ir_emitter.cc:4087) ShapeUtil::SameElementType(operands[0]->shape(), operand->shape()) 
*** Begin stack trace ***
	__libc_start_main
	
*** End stack trace ***

... compiled and ran in 0.0334942s.
execution time for runner Host: 0s.
INTERNAL: RET_CHECK failure (xla/service/cpu/ir_emitter.cc:4087) ShapeUtil::SameElementType(operands[0]->shape(), operand->shape()) 
	Failed to execute on Host
```

Analysis:
I think OperandUpcaster + ResultCaster passes should rewrite mixed precision operands/result dot op as the following
```
## from
dot(f16, f32) -> f16
## to
dot(f32, f32) -> f32
```

The dump shows that The result is f32 , but operands are still (f16, f32)
**after_result_caster**
```
### module_0000.module.0003.HLO_passes_through_layout_assignment.after_result_caster.before_rng-expander.txt

HloModule module, entry_computation_layout={(f16[2,16]{1,0}, f32[16,2]{1,0})->f16[2,2]{1,0}}

ENTRY main {
  p0 = f16[2,16]{1,0} parameter(0)
  p1 = f32[16,2]{1,0} parameter(1)
  dot.clone = f32[2,2]{1,0} dot(p0, p1), lhs_contracting_dims={1}, rhs_contracting_dims={0}
  ROOT convert = f16[2,2]{1,0} convert(dot.clone)
}
```
Possible solution:

Run OperandUpcaster + ResultCaster passes two times.
```
## first run
dot(f16, f32) -> f16
## will be converted by result_caster to
dot(f16, f32) -> f32

## second run
dot(f16, f32) -> f32
## will be converted by operand_upcaster to
dot(f32, f32) -> f32
```

**Comment by akuegel** [comment]
Looking at the CPU pipeline, I see that ResultUpcaster runs after OperandUpcaster, and I think this is the pass the turns the dot output shape into f32. So contrary to what the comment in ResultUpcaster says, I think it should run *before* OperandUpcaster for the CPU backend, because it will convert to the higher precision output type, and only then OperandUpcaster will do the right thing.

**Comment by akuegel** [comment]
https://github.com/openxla/xla/pull/14751 should fix it, but currently there are some infrastructure issues so not sure it is possible to land it today

**Comment by akuegel** [comment]
https://github.com/openxla/xla/commit/aff6df7babebae217b043215fafe263af7a1b85a is the merged commit. This should be fixed now.

**Comment by apivovarov** [comment]
Thank you, Adrian!

One question

On some hardware, it might be preferable to avoid operands conversion in the following case:
```
dot(f16, f16) -> f32
```
What do you think about adding a configuration parameter `operands_can_have_lower_precision_than_the_result` to OperandUpcaster to keep the operands untouched in this scenario?

**Comment by akuegel** [comment]
So this can be configured with a filter, see for example here: https://github.com/openxla/xla/blob/main/xla/service/gpu/gpu_compiler.cc#L635

So for the GPU backend, we don't upcast if it is at least Volta and it is a supported matrix multiplication

If you have some adjustments in mind, patches welcome :)
