### ISSUE TITLE
Error reported when building a project using an image

### ISSUE THREAD

**Issue by yanminghui123** [openxla/xla#14781]
I built the project based on build_free_source.md
Perform the following steps
docker run --name xla -w /xla -it -d --rm -v $PWD:/xla tensorflow/build:latest-python3.9 bash
docker exec xla ./configure.py --backend=CPU
docker exec xla bazel build //xla/...  --spawn_strategy=sandboxed --test_output=all
Then it will report errors where the header file cannot be found.
![image](https://github.com/openxla/xla/assets/26594929/5af05c09-322a-4bc3-808b-d95a6907b8ec)
![image](https://github.com/openxla/xla/assets/26594929/f1967013-827e-401c-ab95-8e5b0f359d17)

Attempting to use other images under tensorflow/tensorflow, the environment is also unavailable, and there is no clang in the system directory
![image](https://github.com/openxla/xla/assets/26594929/a24f9af1-ef7f-4632-a143-af0859f16662)

Is there a mirror that can be used directly?

**Comment by akuegel** [comment]
The error with ::testing::status::StatusIs should have been fixed already with https://github.com/openxla/xla/commit/3640a30a2f6e4b89a5b83ccc67c2d92f08b705f5
You may need to rebase to this new version.

Regarding triton_test_utils, I will take a look if this is still an isse.

**Comment by yanminghui123** [comment]
> The error with ::testing::status::StatusIs should have been fixed already with [3640a30](https://github.com/openxla/xla/commit/3640a30a2f6e4b89a5b83ccc67c2d92f08b705f5) You may need to rebase to this new version.
> 
> Regarding triton_test_utils, I will take a look if this is still an isse.

I have updated to the latest code, but there are still some errors during compilation
![image](https://github.com/openxla/xla/assets/26594929/8c2c2c8c-bc07-415c-b43e-102934a54629)
![image](https://github.com/openxla/xla/assets/26594929/feca4770-af8b-4ae3-b31e-c6ced6276d45)

**Comment by akuegel** [comment]
The fix for missing ir_emitter_triton.h header will soon be merged. I will now look into the missing fusions.h header.

**Comment by akuegel** [comment]
With https://github.com/openxla/xla/commit/15f00145af74b2e7f0ae5259cb954995d6221b38 and https://github.com/openxla/xla/commit/3e5c57ef5b78f65ac4855f09734a0435f89fed11 this should hopefully work now.

**Comment by yanminghui123** [comment]
> With [15f0014](https://github.com/openxla/xla/commit/15f00145af74b2e7f0ae5259cb954995d6221b38) and [3e5c57e](https://github.com/openxla/xla/commit/3e5c57ef5b78f65ac4855f09734a0435f89fed11) this should hopefully work now.


It can be compiled successfully, thank you

**Comment by akuegel** [comment]
Thanks for the confirmation
