### ISSUE TITLE
CUDA 12.6 uses PTX ISA version 8.5 not 8.6

### ISSUE THREAD

**Issue by sclarkson** [openxla/xla#16431]
While running JAX compiled with CUDA 12.6, I get error messages to the effect of

```
'+ptx86' is not a recognized feature for this target (ignoring feature)
```

Per the table [here](https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#release-notes-ptx-release-history), both CUDA 12.5 and 12.6 use PTX ISA 8.5, making the calculation below no longer correct.

https://github.com/openxla/xla/blob/ce2fffa8197cf8c8fd463b2f849e68746f4678f6/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc#L302-L318

**Comment by cheshire** [comment]
@beckerhe WDYT?

**Comment by beckerhe** [comment]
I never was a fan of the heuristic but I also don't have a good alternative approach.

For now I will cap the PTX version.

**Comment by sclarkson** [comment]
Haven't tested but I'm reasonably sure that fixed it. Thanks.
