### ISSUE TITLE
Some unusual performance issues I encountered when trying to use the latest OpenXLA

### ISSUE THREAD

**Issue by yulong-chen551** [openxla/xla#16926]
I tried to update to the latest openxla while the xla I used is the version released about half year ago. Before update, I want to know how much performance improvement I will get. So I do some test and encounter some Issues when testing very small clusters.

First, the clusters are very small and the ncu reports that the one's run time is about 4us, but run_hlo_module gives about 100us.

Second, for the clusters above, old version's run_hlo_module gives about 10us while latest run_hlo_module gives about 100us.

Third, when the "--iterations" is set plural, for example 10, the time for the first test is significantly higher than the time for subsequent tests. But the run_hlo_module of old version seemly did not profile like this?

Thanks very much for your answer!!

**Comment by cheshire** [comment]
I don't really follow the question without additional context.
