### ISSUE TITLE
How is the HLO graph being passed around?

### ISSUE THREAD

**Issue by juuso-oskari** [openxla/xla#16932]
I would like to know how the openXLA operates on a code level, bit in the spirit of https://github.com/tensorflow/tensorflow/issues/9194 (but that answer is from the tensorflow xla, old, and unsolved). Is there anything you might suggest to help to understand, like e.g. how to print the functions that get called when a input HLO graph gets optimized by the xla and gets emitted as llvm IR. This would make it much more easy to understand the functional structure of the xla repo. Or is it the only way to start reading the files and figuring out what gets called by what and in which order?

**Comment by cheshire** [comment]
HLO is an IR, and different passes modify it. You could run with env var `XLA_FLAGS=--xla_dump_to=<folder>`, that will dump IR before/after optimizations. Adding `--xla_dump_hlo_pass_re=.*` (or a regular expression matching interesting passes name from the pipeline in `gpu_compiler.cc`) would show you IR before/after every matched pass.
