### ISSUE TITLE
Does this project target MPS or ml core platform for apple silicon ?

### ISSUE THREAD

**Issue by okpatil4u** [openxla/xla#1788]
As the title says. I am not sure if the question is relevant or not. But I have seen relevant threads such as this.

https://github.com/google/jax/issues/8074

Will this platform enable accelerating either training or inference on apple silicon architecture ?

**Comment by tpopp** [comment]
XLA:CPU would work but has not been fully tuned for M1, but we can't target the ML accelerator or the GPU in M1.  Contributions are of course welcome to improve any of those use cases.

https://github.com/openxla/iree has made more efforts in this direction it looks like (Stella in your linked thread having the context on that).

(I'm closing this in interest of bug tracking but please reopen as appropriate)

**Comment by mattjj** [comment]
I'm not too familiar with the technical details here, but at WWDC Apple just announced [a new plug-in for JAX on Metal](https://developer.apple.com/metal/jax/).
