### ISSUE TITLE
[Support request] Concatenate fusion failed to lower to LLVM IR

### ISSUE THREAD

**Issue by aboubezari** [openxla/xla#19499]
Hey all, I'm working on compiling a diffusion model with XLA for the CUDA backend. I've run `xla_compile` and hit the following error: 
```
loc("input_concatenate_fusion.1.remat2"): error: cannot be converted to LLVM IR: missing `LLVMTranslationDialectInterface` registration for dialect for op: func.func
```
We've been able to track this function down in the MLIR module before LLVM, and we noticed that it's not being replaced by `llvm.func` or inlined. 

Here's the function header:
```
module attributes {dlti.dl_spec = #dlti.dl_spec<#dlti.dl_entry<index, 32 : i32>>} {
  func.func @input_concatenate_fusion_1_remat2(%arg0: !llvm.ptr {llvm.align = 128 : index, llvm.dereferenceable = 40960 : index, xla.slice_index = 0 : index}) attributes {xla.entry} {
```
And here's the entire function definition (unfortunately we can't share the whole model since it's proprietary but we can see what we can do as needed!): https://gist.github.com/aboubezari/b73bbdf725519f02707636fc595ef849

Any pointers, ideas, or potential workarounds would be great! We're happy to collaborate to arrive at a solution :) Thanks!

**Comment by aboubezari** [comment]
cc @pifon2a would you be able to take a look?

**Comment by aboubezari** [comment]
Thanks @pifon2a! 
I've added the definitions of all 2 functions calls here: https://gist.github.com/aboubezari/57980e9c11fded106bc03d5cf7e6547e
Let me know if you need anything else.

**Comment by pifon2a** [comment]
Could you also paste the HloFusionInstruction? 

in `mlir_fusion_emitter.cc` there is an `EmitMlir` method. You can log it there. 

```
absl::Status MlirFusionEmitterBase::EmitMlir(
    mlir::ModuleOp module, FuncOp entry_function,
    const HloFusionInstruction& fusion) const {
 
```

That way I will be able to run it end-to-end to confirm that the bug is fixed.

**Comment by aboubezari** [comment]
Sure, what would be the best way to log it? I tried using `ToString` and all I got was this: 
```
%input_concatenate_fusion.1.remat2 = f32[128,20,4]{2,1,0} fusion(), kind=kInput, calls=%fused_concatenate.1.clone.clone
```

**Comment by pifon2a** [comment]
I used 

```
 std::cerr << fusion.fused_instructions_computation()->ToString() << "\n";
```

**Comment by aboubezari** [comment]
Great, that worked! Here's the fusion definition: https://gist.github.com/aboubezari/d5adb5329df20c18063118b5844cfdee
Let me know if you need anything else.

**Comment by pifon2a** [comment]
`xla-gpu-lower-tensors` pass fails to converge because of IfOp canonicalization pattern(s). I tried commenting out `ConvertTrivialIfToSelect` pattern in SCF.cpp and it worked. I am working on a fix.

**Comment by pifon2a** [comment]
https://github.com/openxla/xla/pull/19648 this should fix the issues. Please, let me know if it worked for you.

**Comment by boubezariali** [comment]
> #19648 this should fix the issue. Please, let me know if it worked for you.

This fixed the compilation crash!! Thank so much @pifon2a!

**Comment by boubezariali** [comment]
We can go ahead and close this ticket. Appreciate the quick response and resolution.
