### ISSUE TITLE
Pallas/Triton gives incorrect result on Nvidia H100 GPU

### ISSUE THREAD

**Issue by jaro-sevcik** [openxla/xla#19780]
After the commit https://github.com/openxla/xla/commit/2354d4a95b232d0676e4fb4a55db97404f4bf8ab, the Pallas/Triton kernel below starts returning wrong results on H100.

JAX repro:

```python
import jax
import jax.numpy as jnp
from jax.experimental import pallas as pl

def mha_forward_kernel(
    q_ref,
    k_ref,
    v_ref,
    o_ref,  # Output
):
    q = pl.load(q_ref, (pl.dslice(0, 64), pl.dslice(None)))
    k = pl.load(k_ref, (pl.dslice(None), pl.dslice(0, 64)))
    qk = pl.dot(q, k).astype(jnp.bfloat16)
    v = pl.load(v_ref, (pl.dslice(0, 64), pl.dslice(0, 128)))
    o = pl.dot(qk, v).astype(jnp.bfloat16)
    pl.store(o_ref, (pl.dslice(0, 64), pl.dslice(None)), o)

q = jnp.ones((64, 128), dtype=jnp.bfloat16)
k = jnp.ones((128, 64), dtype=jnp.bfloat16)
v = jnp.ones((64, 128), dtype=jnp.bfloat16)
r = pl.pallas_call(
        mha_forward_kernel,
        grid=(1,),
        in_specs=[
            pl.BlockSpec((64, 128), lambda _: (0, 0)),
            pl.BlockSpec((128, 64), lambda _: (0, 0)),
            pl.BlockSpec((64, 128), lambda _: (0, 0)),
        ],
        out_specs=pl.BlockSpec((64, 128), lambda _: (0, 0)),
        compiler_params=dict(triton=dict(num_warps=8)),
        out_shape=jax.ShapeDtypeStruct(shape=(64, 128), dtype=q.dtype),
        name="mha_forward",
    )(q, k, v)
print(r)
```

Before https://github.com/openxla/xla/commit/2354d4a95b232d0676e4fb4a55db97404f4bf8ab, the program outputs (the correct result):
```
[[8192 8192 8192 ... 8192 8192 8192]
 [8192 8192 8192 ... 8192 8192 8192]
 [8192 8192 8192 ... 8192 8192 8192]
 ...
 [8192 8192 8192 ... 8192 8192 8192]
 [8192 8192 8192 ... 8192 8192 8192]
 [8192 8192 8192 ... 8192 8192 8192]]
```

After https://github.com/openxla/xla/commit/2354d4a95b232d0676e4fb4a55db97404f4bf8ab, the program outputs (a wrong result):
```
[[4128 4128 4128 ... 4128 4128 4128]
 [64 64 64 ... 64 64 64]
 [4128 4128 4128 ... 4128 4128 4128]
 ...
 [4128 4128 4128 ... 4128 4128 4128]
 [64 64 64 ... 64 64 64]
 [4128 4128 4128 ... 4128 4128 4128]]
```

I should also note that this only happens with `num_warps=8`; the program works correctly with `num_warps=4`.

**Comment by Moerafaat** [comment]
Leaving here same updates for visibility beyond chat.

I replicated the issue and observe the same results. I checked against the current integration and it still produces the same results. I also cherry-picked a few commits ahead of the current integration that sounded like "fixes" to me but they also didn't affect the results.

My investigations show that this is the culprit commit https://github.com/triton-lang/triton/commit/49266aa908d29a7029348ff480a75a3ea4d6e704#diff-6bfcb28073243e2d4b37561063ffb236c6f62b497c236ea0afa8d919735db68cL730

A bug should be filed against OAI Triton with an upstream reproducer.

**Comment by Moerafaat** [comment]
I filed a bug upstream https://github.com/triton-lang/triton/issues/5265 and a proposed fix is already on the way. I will cherry-pick the fix and unblock the failure once confirmed that it works.

**Comment by Moerafaat** [comment]
Fix landed here https://github.com/openxla/xla/commit/3b8d818d9c222f5ab6cd27070846ac65b7d7a475. I will close the bug once confirmed to be fixed from your side @jaro-sevcik

**Comment by Moerafaat** [comment]
Marking this fixed. Please reach out if there is still an issue.
