### ISSUE TITLE
//xla/stream_executor/cuda:compilation_provider_test should be skipped by on CPU builds

### ISSUE THREAD

**Issue by majnemer** [openxla/xla#19829]
I configured XLA via
```shell
./configure.py --backend=CPU
```

I ran all tests via:
```shell
bazel test -c opt //xla/...
```

This ended up running `//xla/stream_executor/cuda:compilation_provider_test` which is a bit surprising. The test failed like so:
```
Running main() from gmock_main.cc
[==========] Running 17 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 17 tests from CompilationProviderTest/CompilationProviderTest
[ RUN      ] CompilationProviderTest/CompilationProviderTest.NameIsNotEmpty/0
xla/stream_executor/cuda/compilation_provider_test.cc:57: Failure
Value of: _status_or_value0.status().ok()
  Actual: false
Expected: true
NOT_FOUND: Couldn't find a suitable version of ptxas. The following locations were considered: /does/not/exist/bin/ptxas, ./ptxas, ...
```

I think it's missing some `tag` or `backend` option to `xla_cc_test`.

**Comment by beckerhe** [comment]
Right. This tests needs to be tagged `gpu`. I'm going to take care of that

**Comment by beckerhe** [comment]
Turns out I already added the tags in https://github.com/openxla/xla/commit/3fb062f9bb9419449272463cc4aad43642f168ab for a different reason.

I got merged a few moments ago, so this should be fixed.
