### ISSUE TITLE
GPU fusion kernel with transpose operator shows bad data locality of I/O tensors 

### ISSUE THREAD

**Issue by shawnwang18** [openxla/xla#2103]
We observed a case that XLA's fusion kernel is very slow due to bad data locality of DRAM access for I/O tensors.  The case is from stable diffusion model.   

The fused kernel has has theoretical read traffic of 2.64GB , and write traffic of 0.66GB. 
But from nsight-compute profiler results, we observed the kernel has total 22.14GB DRAM read traffic, which is 8.4x theoretical traffic. This makes the fusion kernel quite slow, kernel time is about 44ms, which takes about 24% of total step time. 

Seems that the data locality is due to transpose operator in the fusion graph. 

Attaching the HLO graph and profiler results here: https://drive.google.com/drive/folders/14KNN4vLKtVNzXhYjnmv3_lJEAViDlgcE

Please check the `fused_computation.1072` kernel in HLO dump file `xla-nightly-float32-n4/module_0798.pjit_update.sm_8.0_gpu_after_optimizations`

**Comment by cheshire** [comment]
Tracked internally in b/274910587

**Comment by akuegel** [comment]
I measured a > 2x speedup with this patch: https://github.com/openxla/xla/pull/2125

**Comment by shawnwang18** [comment]
That is great! Thanks for this quick response.

**Comment by akuegel** [comment]
I found a way to avoid the regression in the one benchmark that had the biggest regression while keeping the improvement for stable diffusion, but there is still another benchmark that shows a 2% regression. Will investigate tomorrow.

**Comment by akuegel** [comment]
Correct.
