### ISSUE TITLE
How to prevent instructions from being CSE?

### ISSUE THREAD

**Issue by LiuXiaoxuanPKU** [openxla/xla#2433]
Hi! Thanks for the repo! I am currently experimenting with XLA optimization passes and am interested in trying out customized optimization. In order to implement these optimizations, we need to add some instructions immediately prior to the SPMD pass. However, we have observed that these instructions are being deleted by the subsequent CSE passes.

We were wondering if there are any flags that could be used to disable optimization on specific instructions. We appreciate any guidance or suggestions you may have regarding this matter.

**Comment by tpopp** [comment]
Why does the CSE prevent you from attempting your optimizations, as the instructions are still there, but in a single place rather than multiple? Hopefully they would be always useful, or you would generate some additional code per consumer?

**Comment by tpopp** [comment]
I'm closing this to keep action items clear, but feel free to re-open if you feel there is more to discuss.
