### ISSUE TITLE
Will XLA support dynamic shapes?

### ISSUE THREAD

**Issue by XinboZhao** [openxla/xla#2598]
XLA will re-compile everytime a new shape appears. Will XLA support dynamic shapes? Is there a roadmap?
Or could you please tell me where to find the roadmap the XLA?

**Comment by cheshire** [comment]
Right now, only bounded dynamic shapes are supported.

**Comment by XinboZhao** [comment]
Thanks. I have found some links about 'bounded dynamic shapes'. And I probably understand it.
https://github.com/pytorch/xla/issues/3884
https://github.com/openxla/stablehlo/pull/194
