### ISSUE TITLE
Use of preprocessor directive in function-like macro argument list is undefined behavior

### ISSUE THREAD

**Issue by cloudhan** [openxla/xla#2845]
The `#if` directives nested in `TF_ASSIGN_OR_RETURN` is not conform to the C standard.

https://github.com/openxla/xla/blob/f7eccd15353e41a23c91daeb70ba37931f91e7c9/xla/stream_executor/cuda/cuda_dnn.cc#L3952-L3961

And this is causing excessive compiling issue with msvc

```
warning C5101: use of preprocessor directive in function-like macro argument list is undefined behavior
```

FYI:
https://wiki.sei.cmu.edu/confluence/display/c/PRE32-C.+Do+not+use+preprocessor+directives+in+invocations+of+function-like+macros
https://stackoverflow.com/questions/64452244/c-c-how-should-preprocessor-directive-work-on-macros-argument-list

**Comment by cloudhan** [comment]
Just as a remind, this problem has also occurred at
https://github.com/openxla/xla/blob/2b0fcca9dc281a4aaf7edf8ad0b5d5ee68d37511/xla/service/gpu/runtime/kernel_launch.cc#L120-L139
previously, but it was accidentially fixed in later changes.

**Comment by tpopp** [comment]
Hello and thank you for the report. To save myself some compile cycles, can you share if this is the only occurrence or if there are more that I should be looking for?

**Comment by cloudhan** [comment]
The file [cuda_dnn.cc](https://github.com/openxla/xla/blob/f7eccd15353e41a23c91daeb70ba37931f91e7c9/xla/stream_executor/cuda/cuda_dnn.cc) and only this file is non-conformal, and it contains multiple occurrences.  Just search `#if` should nail all thoes issues down.

**Comment by cloudhan** [comment]
Fix verified.
