### ISSUE TITLE
How to easily enable OpenXLA in TensorFlow?

### ISSUE THREAD

**Issue by shshao-iceice** [openxla/xla#3043]
Hi, we are interested in using OpenXLA (MHLO or StableHLO) in TensorFlow, is there an easy way to enable it easily for testing in TensorFlow? Either Python or C++ API is fine. We just want to quickly get a sense whether OpenXLA is faster or slower than traditional XLA.

**Comment by cheshire** [comment]
@julianwa for a more precise answer, but I do not think the bridging work has been done from TF.
