### ISSUE TITLE
Build error: ‘ASSERT_OK_AND_ASSIGN’ was not declared in this scope

### ISSUE THREAD

**Issue by joker-eph** [openxla/xla#3518]
I have a build error locally right now somehow:

```
xla/pjrt/gpu/se_gpu_pjrt_client_test.cc:366:3: error: ‘ASSERT_OK_AND_ASSIGN’ was not declared in this scope; did you mean ‘TF_ASSERT_OK_AND_ASSIGN’?
  366 |   ASSERT_OK_AND_ASSIGN(
      |   ^~~~~~~~~~~~~~~~~~~~
      |   TF_ASSERT_OK_AND_ASSIGN
```

I don't know where is this `ASSERT_OK_AND_ASSIGN` macro supposed to be defined? 
There are 3 hits in the codebase right now (all in the same file): 

```
$ git grep ASSERT_OK_AND_ASSIGN | grep -v TF_ASSERT_OK_AND_ASSIGN
xla/pjrt/gpu/se_gpu_pjrt_client_test.cc:  ASSERT_OK_AND_ASSIGN(
xla/pjrt/gpu/se_gpu_pjrt_client_test.cc:  ASSERT_OK_AND_ASSIGN(
xla/pjrt/gpu/se_gpu_pjrt_client_test.cc:  ASSERT_OK_AND_ASSIGN(
```

**Comment by joker-eph** [comment]
Can you check why it isn't built by the CI?

**Comment by ddunl** [comment]
Yeah that's a good point, I'll look into that as well

**Comment by ddunl** [comment]
Seems like it's because the CI looks for `requires-gpu` rather than `requires-gpu-nvidia`.  Testing that change now

**Comment by ddunl** [comment]
Now that I've changed the tags on the CI I see that there's further errors, so reopening. I'll try to fix these today

**Comment by ddunl** [comment]
With 93559da32e664b080cd2776bed1216bd8deec2d4 and another commit that is submitted internally but Copybara is taking it's time on the PJRT OSS failures should be fixed and in the future they'll run on the Kokoro builds. Thanks for reporting this!
