### ISSUE TITLE
no .gitignore in xla?

### ISSUE THREAD

**Issue by i-chaochen** [openxla/xla#4282]
I notice there is no ```.gitignore``` file in xla repo, which means I need to manually rm bazel-bin, bazel-out, bazel-testlogs and bazel-xla each time before I submit the PR to XLA.

All other openxla projects, e.g., IREE, openxla-pjrt-plugin, stablehlo, openxla-benchmark have ```.gitignore```, TensorFlow of course has it as well.

Wondering is any parciular reason xla doesn't have ```.gitignore```?

Thanks

**Comment by cheshire** [comment]
There's no particular reason, contributions welcome!

**Comment by i-chaochen** [comment]
https://github.com/openxla/xla/pull/4285/files
