### ISSUE TITLE
XLA:GPU incorrect optimization of boolean operators

### ISSUE THREAD

**Issue by jakevdp** [openxla/xla#4803]
Reported in https://github.com/google/jax/issues/17003. The output is as expected on CPU, but incorrect under JIT on GPU (tested on a Colab T4 GPU runtime, with jax/jaxlib v0.4.14):
```python
import jax
import jax.numpy as jnp

def less_equal_2D(x, y):
    return (x[0] < y[0]) | ((x[0] == y[0]) & (x[1] <= y[1]))

x = jnp.array([0, 1])
y = jnp.array([0, 0])

print(jax.devices())
# [gpu(id=0)]

print(less_equal_2D(x, y))
# False

print(jax.jit(less_equal_2D)(x, y))
# True
```

**Comment by akuegel** [comment]
This should be fixed now with https://github.com/openxla/xla/commit/ce0a31d994cf2a3ae85bf0b3821518682bcd223f
