### ISSUE TITLE
Custom attributes for HLO Module

### ISSUE THREAD

**Issue by sogartar** [openxla/xla#5424]
I want to be able to have some arbitrary attributes associated with an HLO Module. This is in the context of doing conversions StableHLO -> HLO -> StableHLO. I want somewhere to put custom module attributes that survive the round-trip conversion.
For HLO instructions there is the `mhlo.frontend_attributes` attributed in MLIR. There should be something equivalent for the HLO Module.

I can write a PR for this if there is no opposition to such a feature.

**Comment by cheshire** [comment]
Maybe you could provide a bit more information about your use case?

**Comment by cheshire** [comment]
@burmako WDYT?

I don't have immediate concerns about allowing FrontendAttributes attached to HloModule.

**Comment by burmako** [comment]
Apologies for the very late reply! I have no concerns either. @sogartar Thank you for the pull request, and @cheshire thank you for reviewing it 🙏

**Comment by penpornk** [comment]
Closing this issue since PR #5491 went in.
