### ISSUE TITLE
Miscompilation for reduction over negative zeros

### ISSUE THREAD

**Issue by hawkinsp** [openxla/xla#5544]
The following JAX program produces wrong results on A100 and V100:

```
import jax.numpy as jnp
x = jnp.zeros((8193,)) * -1
jnp.max(x)
# return -inf
```

Interestingly, if the input size is 8192, we get the expected result (-0).

The HLO JAX runs is unremarkable:
```
HloModule jit__reduce_max, entry_computation_layout={(f32[8193]{0})->f32[]}, allow_spmd_sharding_propagation_to_output={true}

region_0.3 {
  Arg_0.4 = f32[] parameter(0)
  Arg_1.5 = f32[] parameter(1)
  ROOT maximum.6 = f32[] maximum(Arg_0.4, Arg_1.5), metadata={op_name="jit(_reduce_max)/jit(main)/reduce_max[axes=(0,)]" source_file="experimental/users/phawkins/jax/lingvo_badness.py" source_line=49}
}

ENTRY main.8 {
  Arg_0.1 = f32[8193]{0} parameter(0), sharding={replicated}
  constant.2 = f32[] constant(-inf)
  ROOT reduce.7 = f32[] reduce(Arg_0.1, constant.2), dimensions={0}, to_apply=region_0.3, metadata={op_name="jit(_reduce_max)/jit(main)/reduce_max[axes=(0,)]" source_file="experimental/users/phawkins/jax/lingvo_badness.py" source_line=49}
}
```

This appears to be an XLA miscompilation.

**Comment by hawkinsp** [comment]
Originally filed as https://github.com/google/jax/issues/17531

**Comment by cheshire** [comment]
A while ago it was proposed to reject HLOs where the initial value is not an identity, is it a duplicate by chance?

**Comment by hawkinsp** [comment]
-inf *is* the identity for a max reduction.

**Comment by cheshire** [comment]
Ah apologies, I've looked at the issue title about negative zeros, and not the HLO dump. Makes sense now.

**Comment by hawkinsp** [comment]
@cheshire Any progress?

**Comment by cheshire** [comment]
Should have been fixed by https://github.com/openxla/xla/commit/9cfee329c97d1272320dc4a830581ad72fb03ad9, but this bug wasn't marked as fixed. @sergeykozub can we close this?
