### ISSUE TITLE
[Q] Any plans to switch to C++20 by default ?

### ISSUE THREAD

**Issue by apivovarov** [openxla/xla#5615]
OpenXLA head still uses C++17 by default - https://github.com/openxla/xla/blob/main/.bazelrc#L353

Do you have any plans to switch to C++20 by default ?

**Comment by d0k** [comment]
OpenXLA can only switch to C++20 when it's consumers (PyTorch, Tensorflow, ...) support C++20 in their build environments, so we have to be conservative here. That in turn requires the widespread availability of C++20 toolchains and dropping support for Cuda 11 which doesn't support C++20.

It's really hard to give an estimate on when that might happen, but it's unlikely before mid 2024.
