### ISSUE TITLE
error: 'Py_TPFLAGS_HAVE_VECTORCALL' was not declared in this scope; did you mean 'Py_TPFLAGS_HAVE_VERSION_TAG'?

### ISSUE THREAD

**Issue by jeffhataws** [openxla/xla#5691]
When I follow the contribution guide and build top-of-tree (ie commit 83d9984673b6a954ccdc034c67f33c2a85e2ad32), I keep seeing errors like below:

```
bazel build //xla/...  --spawn_strategy=sandboxed --test_output=all
```

```
xla/python/pmap_lib.cc:988:43: error: 'Py_TPFLAGS_HAVE_VECTORCALL' was not declared in this scope; did you mean 'Py_TPFLAGS_HAVE_VERSION_TAG'?
  988 |                      Py_TPFLAGS_HAVE_GC | Py_TPFLAGS_HAVE_VECTORCALL;
      |                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                           Py_TPFLAGS_HAVE_VERSION_TAG

```

Do you know what I am missing?

I am using the same docker as from pytorch/xla contribution guide (https://github.com/pytorch/xla/blob/master/CONTRIBUTING.md#building-manually)

**Comment by JackCaoG** [comment]
hmm, would it build if you use https://github.com/pytorch/xla/blob/master/WORKSPACE#L48C49-L48C89 this commit? I think this is pin to ~ 08/24. Everytime we update openxla we need to deal with some weird compilation errors, I am not sure if this one is new. If it is we need to somehow fix it in next pin update.

**Comment by jeffhataws** [comment]
By following https://github.com/openxla/xla/blob/main/docs/developer_guide.md and using the tensorflow docker, I have gotten past this error. Thanks!
