### ISSUE TITLE
[Epic] XLA:GPU Thunk runtime consolidation

### ISSUE THREAD

**Issue by ezhulenev** [openxla/xla#5757]
Thunk runtime was semi-deprecated and abandoned for about a year, we need to spend some time cleaning it up and preparing for the new features we want to add to in in 2023-2034
```[tasklist]
### Tasks
- [ ] https://github.com/openxla/xla/issues/5758
- [ ] https://github.com/openxla/xla/issues/6224
```

**Comment by anlunx** [comment]
Add a task for bringing back thunk emitter
