### ISSUE TITLE
[xla:gpu] SPMD pass is not partition aware for reduce op

### ISSUE THREAD

**Issue by wenscarl** [openxla/xla#5963]
SPMD pass is not partition-aware for reduce op. This creates a perf impact in FP8 cases.  o give a example, the operand of reduce has some specific partition specification, e,g. replicated. When the tensor is operated upon, all devices will perform the same computations on the entire tensor, which is not the most efficient. Instead, it's more beneficial to include a combination of slicing and all-reduction operations to complete the task.

![image](https://github.com/openxla/xla/assets/25590028/05a22fe2-ff9d-4df0-9e63-0eb6711620c2)
A simple reproducer could be:
```python
"""Tests for the fp8 layers with partitioning."""
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import numpy as np
import argparse
import optax

import jax
import jax.numpy as jnp
from jax import random

from flax import linen as nn

# Sharding related
from jax.experimental.pjit import pjit
from jax.sharding import Mesh
from jax.experimental import mesh_utils
from flax import linen as nn
from flax.linen import spmd # Flax Linen SPMD.
from typing import (Iterable, Tuple)
from typing import Iterable, Tuple
from flax.linen import partitioning as nn_partitioning
param_with_axes = nn_partitioning.param_with_axes
from flax.training import train_state

# Type annotations
Array = jnp.ndarray
Dtype = jnp.dtype
PRNGKey = jnp.ndarray
Shape = Iterable[int]


def _normalize_axes(axes: Iterable[int], ndim: int) -> Tuple[int]:
  # A tuple by convention. len(axes_tuple) then also gives the rank efficiently.
  return tuple([ax if ax >= 0 else ndim + ax for ax in axes])

def _canonicalize_tuple(x):
  if isinstance(x, Iterable):
    return tuple(x)
  else:
    return (x,)


parser = argparse.ArgumentParser(description='Benchmark a basic encoder layer')
parser.add_argument('--d', type=int, help='matrix dim')
args = parser.parse_args()

dim = args.d

class DenseGeneral(nn.DenseGeneral):
  kernel_axes: Tuple[str, ...] = ()
  bias_axes: Tuple[str, ...] = ()

  @nn.compact
  def __call__(self, inputs: Array) -> Array:
    original_shape = inputs.shape
    assert len(original_shape) >= 2

    features = _canonicalize_tuple(self.features)
    axis = _canonicalize_tuple(self.axis)

    inputs = jnp.asarray(inputs, self.dtype)
    axis = _normalize_axes(axis, inputs.ndim)

    kernel_param_shape = (np.prod([inputs.shape[ax] for ax in axis]),
                          np.prod(features))

    kernel = param_with_axes(
        'kernel',
        self.kernel_init,
        kernel_param_shape,
        self.param_dtype,
        axes=self.kernel_axes)
    kernel = jnp.asarray(kernel, self.dtype)

    if self.use_bias:
      bias = param_with_axes(
          'bias',
          self.bias_init,
          (np.prod(features),),
          self.param_dtype,
          axes=self.bias_axes)
      bias = jnp.asarray(bias, self.dtype)
    else:
      bias = None

    inputs, kernel, bias = nn.dtypes.promote_dtype(inputs, kernel, bias,
                                                   dtype=self.dtype)

    inputs = jnp.reshape(inputs, (-1, np.prod([inputs.shape[ax] for ax in axis])))
    if self.dot_general_cls is not None:
      dot_general = self.dot_general_cls()
    else:
      dot_general = self.dot_general

    out = dot_general(
        inputs,
        kernel,
        ((axis, 0), ((), ())),
        precision=self.precision,
    )

    # Reshape back the outputs.
    out = jnp.reshape(out, (*original_shape[0:-len(axis)], *tuple(features)))

    return out


def run():
  rules = (('hidden', 'model'),)
  device_mesh = mesh_utils.create_device_mesh((2, 2))
  mesh = Mesh(devices=device_mesh, axis_names=('data', 'model'))

  model = DenseGeneral(dim , kernel_axes=('hidden', 'mlp'), dot_general_cls=nn.Fp8DenseGeneralOp, dtype=jnp.float16)

  x = random.normal(random.PRNGKey(0), (dim, dim ), dtype=jnp.float16)
  k = random.PRNGKey(0)

  spmd.set_logical_axis_rules(rules)

  initialized_vars = model.init(k, x)
  opt = optax.adam(learning_rate=0.1)
  ts_args = {'tx': opt, 'apply_fn': model.apply}
  ts_args['params'] = initialized_vars
  state = train_state.TrainState.create(**ts_args)

  def step_fn(state, x):
    def loss_fn(vars, x):
      x = spmd.with_logical_constraint(x, ('batch', 'embed'))
      y = state.apply_fn(vars, x)
      loss = y
      return jnp.sum(loss)
    grad_fn = jax.value_and_grad(loss_fn, argnums=[0,1])
    loss, grads = grad_fn(state.params, x)
    state = state.apply_gradients(grads=grads[0])
    return state, loss

  pjit_step_fn = pjit(
      step_fn
  )
  warmup_iters = 20

  with mesh:
    # Warmup runs
    for _ in range(warmup_iters):
      state, loss = pjit_step_fn(state, x)

  return loss

print(run())

```
Note: To run the reproducer, latest FLAX is necessary.
cc @kaixih @reedwm @jurahul @philipphack @nouiz

**Comment by nouiz** [comment]
I discussed offline with @wenscarl. We need to document better what people should expect from the XLA sharding propagation.
I suggested him a way to manually build an jax graph that would do what he want. He will try that.

**Comment by jurahul** [comment]
Hi @wenscarl, I looked at the PR and it seems that the SPMD partitioner can generate the desired code (local reduce + all-reduce) if the input to the reduce is partitioned. Would adding a manual sharding on the input to the reduce operation be a better way to have SPMD generate the desired code as opposed to adding a new pass. The issue is the a lot of replicated operations can be re-partitioned to use a similar scheme, and it won't be feasible to add all such passes. In addition, in terms of responsibilities, SPMD partitioning is responsible for this and we should try to not scatter the distribution logic to more passes if possible.

Please let me know if sharding the input to reduce and having the partitioner generate the code is feasible.

**Comment by jurahul** [comment]
The SPMD partitioning unit test `SpmdPartitioningTest.TiledToReplicatedReduce/V1` can demonstrate SPMD generating the code which I think the pass is trying to generate.

**Comment by wenscarl** [comment]
Hi, @jurahul I agree with you that it's better to move this logic to spmd partitioner. I am still figuring out where to place this logic in spmd partitoner. As I understand from `SpmdPartitioningTest.TiledToReplicatedReduce/V1`, the input to reduce is already sharded and output to reduce is replicated, so that partitioner could generate necessary dynamic-slices. For the situation in this issue, since the input is replicated, an additional sharded tensor would be inserted to the input of reduce, to end up with something like:
`param(replicated)->abs->copy(sharded)>reduce->scalar`, where `copy(shareded)` is the only change. Then the partitioner inserts dynamic-slices and add-reduce if necessary.

**Comment by nouiz** [comment]
What `copy(shareded)`? A normal d2d copy? Why it is needed?
Also, I'm not sure the partitioner is the right place. This is an optimization. We could want to not do it.
There is no guarantee that this is always faster. So being able to disable it sound like a good properties to have.

**Comment by jurahul** [comment]
I feel that sharding the input is the right thing. Imagine if we have a very large add of 2 replicated tensors. Its possible that it may be more optimal to instead shard the tensor, and then each device does a shard of the add, then the data is all-gathered. Should this be implemented as a separate optimization or should this be left to the user to adjust their sharding so that the add is sharded this way by the SPMD partitioner?

**Comment by wenscarl** [comment]
>I feel that sharding the input is the right thing.
One concern is that the input may have other consumer in which case `replicated` or another kind of sharding is optimal.
> What copy(shareded)? A normal d2d copy? Why it is needed?
The copy(sharded) is to address the above concert to limit the effect only to reduce.

**Comment by nouiz** [comment]
I see 3 high-levels direction to implement a fix here:
1) Update the python code to use jax.lax.p* to manually do the computation you want.
2) An XLA optimization pass + a threshold flag.
3) In the SPMD partitioner.

1 looks good, but short sighted. 2 looks good but more complex. 3 doesn't look good to me.

**Comment by wenscarl** [comment]
As suggested by @nouiz , the following can serve the purpose,
The old way is
```
amax_update = jnp.max(jnp.abs(x)).astype(scale.dtype)
```
97ms/step
after change, it becomes
```
tmp = jnp.abs(x)
tmp = spmd.with_logical_constraint(tmp, ('data', 'model'))
amax_update = jnp.max(tmp)
```
91ms/step
The change doesn't affect other part of the graph. Closing.
