### ISSUE TITLE
Which models benefit from the introduction of cuda graph?

### ISSUE THREAD

**Issue by Tengfei09** [openxla/xla#6195]
I noticed that XLA runtime has introduced the CUDA graph mechanism recently. A simple question is which models benefit from the introduction of the cuda graph? especially large language models (LLMs).

BTW, a naive question: how do we enable cuda graph when running a Jax model?

`
--xla_gpu_graph_level=2 --xla_gpu_graph_enable_concurrent_region 
` is it correct?

**Comment by Tengfei09** [comment]
I'd like to measure the impact of the CUDA graph on some JAX models. As you said, --xla_gpu_graph_level=1 is enabled by default. If I want to disable this feature, just set --xla_gpu_graph_level=0. is it correct?

**Comment by cheshire** [comment]
Exactly.

**Comment by Tengfei09** [comment]
Could you provide an open-source JAX model name(from HG or github) that benefits from the CUDA graph greatly? thx @cheshire
