### ISSUE TITLE
LoopDoubleBufferTransformer makes spurious assumptions

### ISSUE THREAD

**Issue by bchetioui** [openxla/xla#6353]
While debugging another issue in the LoopDoubleBufferTransformer, I wrote the following test case:

```
HloModule loop_unrolling_nested_while_loop_remains_flattened

condition_nested {
  input_tuple = (s32[]) parameter(0)
  cond = s32[] get-tuple-element(input_tuple), index=0
  trip_count = s32[] constant(10)
  ROOT done = pred[] compare(cond, trip_count), direction=LT
}

body_nested {
 input_tuple = (s32[]) parameter(0)
 cond = s32[] get-tuple-element(input_tuple), index=0
 one = s32[] constant(1)
 cond_plus_1 = s32[] add(cond, one)
 ROOT output = (s32[]) tuple(cond_plus_1)
}

condition {
  input_tuple = (s32[]) parameter(0)
  cond = s32[] get-tuple-element(input_tuple), index=0
  trip_count = s32[] constant(10)
  ROOT done = pred[] compare(cond, trip_count), direction=LT
}

body {
  input_tuple = (s32[]) parameter(0)
  ROOT output = (s32[]) while(input_tuple), condition=condition_nested, body=body_nested
}

ENTRY main {
 param_0 = (s32[]) parameter(0)
 ROOT while = (s32[]) while(param_0), condition=condition, body=body, backend_config={"known_trip_count":{"n":"10"}}
}
```

This HLO is valid, but running it through the LoopDoubleBufferTransformer causes a crash because the pass assumes that while loop bodies are rooted in tuple instructions.

(I can't assign, but @Tixxx since you are the author of the pass :))

**Comment by Tengfei09** [comment]
@Tixxx I also got an unexpected crash with the LoopDoubleBufferTransformer pass when running a FLAN-T5-XL model.

**Comment by Tixxx** [comment]
> @Tixxx I also got an unexpected crash with the LoopDoubleBufferTransformer pass when running a [FLAN-T5-XL](https://github.com/google-research/t5x/blob/main/t5x/examples/t5/t5_1_1/xl.gin) model(bfloat16, 32/32).
> 
> failed when running _tuple_simplifer_ pass:
> 
> ```
> jaxlib.xla_extension.XlaRuntimeError: INTERNAL: RET_CHECK failure (external/xla/xla/hlo/ir/hlo_computation.cc:318) IsSafelyRemovable(instruction) Cannot remove instruction: %get-tuple-element.5891 =
> ```

Hi @Tengfei09  would you be able to attach the HLO for your failure? Thanks.

**Comment by Tengfei09** [comment]
@Tixxx After applying your new changes #6377 , this crash disappears. I may get a similar problem. Thanks for your updates.
