### ISSUE TITLE
XlaRuntimeError: INTERNAL: custom_partitioner: UnicodeDecodeError: 'utf-8' codec can't decode byte...

### ISSUE THREAD

**Issue by chaserileyroberts** [openxla/xla#6718]
This error is happening because the backend config string I pass includes bytes that are not valid utf-8 characters. 

My suggested fix is to add `py::bytes(...)` wrapping each of the three uses of `instruction->raw_backend_config_string()` in custom partitioner.

Specifically [here](https://github.com/openxla/xla/blob/ec1d794349b91a38607ef7aa1b75fb4c04ab430e/xla/python/custom_call_sharding.cc#L125) for example.

**Comment by cheshire** [comment]
Thanks a lot! Do you have a repro? Are you interested in sending a PR?
