### ISSUE TITLE
[xla:gpu] Add efficient command buffer updates

### ISSUE THREAD

**Issue by ezhulenev** [openxla/xla#6935]
Today command buffer sequence always updates command buffer with new commands, which can be very inefficient (*). We need to update only commands that have changes, which in `CommandBufferCmd` in practice means that buffer allocation address changed.

We need something like this:

```
class CommandBufferCmd {
  virtual absl::Span<const BufferAllocation::Slice> slices();
};
```

`CommandBufferCmdSequence` + `CommandBufferThunk` should detect if no buffer addresses changes, then there is no need to Update/Record command buffer.

The next step would be to detect which buffer slices changed address, and which commands require update, however it's not clear how critical is that for performance, as in practice likely majority of commands will need an update, and the cost of extra tracking can be too expensive. We need to collect some statistics first to decide if it's worth pursuing at all.

(*) https://github.com/openxla/xla/blob/main/xla/service/gpu/runtime3/command_buffer_cmd.cc#L57-L67

**Comment by tyb0807** [comment]
Marked as done, will open another one for the "next step" if required later
