### ISSUE TITLE
Docker images in the developer guide are stale

### ISSUE THREAD

**Issue by hawkinsp** [openxla/xla#7603]
The GPU docker image mentioned in the developer guide is quite stale, e.g., it has CUDA 11.2 installed which is below the minimum we support these days (11.8).
https://github.com/openxla/xla/blob/main/docs/developer_guide.md#set-up-an-environment

Can we use a fresher image?

**Comment by Micky774** [comment]
More details for this in https://github.com/openxla/xla/issues/7661
