### ISSUE TITLE
Update "build from source" and "developer guide" documentation

### ISSUE THREAD

**Issue by Micky774** [openxla/xla#7661]
There are inconsistencies between the [developer guide](https://github.com/openxla/xla/blob/main/docs/developer_guide.md) and [build from source](https://github.com/openxla/xla/blob/main/docs/build_from_source.md) docs regarding what containers to run. I think this likely stems from https://github.com/openxla/xla/pull/7237 which introduced changes in the [build from source](https://github.com/openxla/xla/blob/main/docs/build_from_source.md) page. Specifically, it changed 
`tensorflow/build:latest-python3.9` to `tensorflow/tensorflow:latest-gpu` for the CPU building instructions, however the comment indicated it was intended to update `tensorflow/tensorflow:devel-gpu` in the GPU section instead.

I would suggest
- [ ] Updating `tensorflow/tensorflow:devel-gpu` to `tensorflow/tensorflow:latest-gpu` in **both pages**
- [ ] Reverting https://github.com/openxla/xla/pull/7237 to change `tensorflow/tensorflow:latest-gpu` to `tensorflow/build:latest-python3.9` for the CPU section (or even perhaps >3.9 if available)
- [ ] Include steps for installing `bazelisk` and missing CUDA deps in the container (ideally the upstream container would be improved, or a custom XLA container would be made, but this is the least invasive way I think)

I'd be happy to open PRs if these are of interest.

Edit: I should probably include that even with `tensorflow/tensorflow:latest-gpu`, the docker image is not enough to build XLA due to missing `bazel`. The first point, therefore, may be okay to ignore for now.

**Comment by cheshire** [comment]
@ddunl for comments

**Comment by syheliel** [comment]
I agree with this. I've just encountered a build failure when following the guide in `developer guide`. The CUDA in ` tensorflow/tensorflow:devel-gpu` is too old(11.2) to build the CUDA fp8 things(because of the Missing header file `cuda_fp8.h`.
