### ISSUE TITLE
Wrong handling of CLI flags in //xla/tools/multihost_hlo_runner:hlo_runner_main

### ISSUE THREAD

**Issue by sergachev** [openxla/xla#7923]
1) Nonexistent flags like --i_am_not_a_flag=123 are silently ignored.
2) The default values of flags do not correspond to the ones printed in --help. Say xla_gpu_enable_triton_gemm is false.

//xla/tools:run_hlo_module has none of these problems.

**Comment by cheshire** [comment]
How do you run it? The flag handling seems identical, I haven't tried in OSS yet, but at least internally it works the same.

**Comment by sergachev** [comment]
`bazel run //xla/tools/multihost_hlo_runner:hlo_runner_main -- --device_type=gpu --i_am_not_a_flag=123 --hlo_file=/tmp/tmp.hlo` (succeeds) vs `bazel run //xla/tools:run_hlo_module -- --platform=cuda --reference_platform= --i_am_not_a_flag=123 /tmp/tmp.hlo` (fails) for example.

**Comment by sergachev** [comment]
The problem with this is that it takes extra effort to find out which flags had effect and which were silently ignored.

**Comment by heinsaar** [comment]
As @cheshire mentioned, running Blaze produces the same result with both:

```
//xla/tools$ blaze run multihost_hlo_runner:hlo_runner_main -- --i_am_not_a_flag=123
...
ERROR: Unknown command line flag 'i_am_not_a_flag'
```
And:
```
//xla/tools$ blaze run :run_hlo_module -- --i_am_not_a_flag=123
...
ERROR: Unknown command line flag 'i_am_not_a_flag'
```
Looks like this must be reproduced using Bazel.

**Comment by sergachev** [comment]
The build system does not matter. `./bazel-bin/xla/tools/multihost_hlo_runner/hlo_runner_main --i_am_not_a_flag=123 --hlo_file=/tmp.hlo` does not fail on the nonexistent flag.

**Comment by sergachev** [comment]
Don't know. I get different output.

```
bazel run xla/tools/multihost_hlo_runner:hlo_runner_main -- --i_am_not_a_flag=123
...
F0000 00:00:1709815816.229516   92650 hlo_runner_main.cc:148] Non-OK-status: xla::FunctionalHloRunner::LoadAndRunAndDump( *client.value(), xla::GetDebugOptionsFromFlags(), preproc_options, raw_compile_options, running_options, {hlo_file}, input_format, dump_output_literal_to, task_id) status: NOT_FOUND: ; No such file or directory
```


```
bazel run xla/tools/multihost_hlo_runner:hlo_runner_main -- --i_am_not_a_flag=123 --hlo_file=/tmp/tmp.hlo
...
(success)
```
