### ISSUE TITLE
[HELP] overlap of communication and computation on GPU

### ISSUE THREAD

**Issue by wbmc** [openxla/xla#8046]
Hello! I'm intrigued by the methods involving the overlap of communication and computation on GPUs. I came across a paper called "Overlap Communication with Dependent Computation via Decomposition in Large Deep Learning Models," which discusses these techniques and their implementation in XLA. Could you kindly inform me if the code for this paper is open source?

**Comment by cheshire** [comment]
Most algorithms should be in the OSS XLA, however, getting them to work well on GPU might require setting custom flags. 

https://github.com/NVIDIA/JAX-Toolbox/blob/main/rosetta/rosetta/projects/pax/README.md#xla-flags gives some example of custom flags which could be used.

**Comment by wbmc** [comment]
> Most algorithms should be in the OSS XLA, however, getting them to work well on GPU might require setting custom flags.
> 
> https://github.com/NVIDIA/JAX-Toolbox/blob/main/rosetta/rosetta/projects/pax/README.md#xla-flags gives some example of custom flags which could be used.

OK, Thanks
