### ISSUE TITLE
mhlo.all_reduce legalize to stablehlo not supported

### ISSUE THREAD

**Issue by eedalong** [openxla/xla#8246]
When converting mhlo to stablehlo, `all_reduce` op is not supported

**Comment by cheshire** [comment]
CC @GleasonK 

Opening an issue on the stablehlo repo might make more sense.

**Comment by GleasonK** [comment]
This is captured in https://github.com/openxla/stablehlo/issues/1370.

I'm guessing this is a multi-operand / multi-result all_reduce, in which case failing to convert is expected. Tuple collectives were added to HLO more recently and have not been standardized in StableHLO yet. There are asks for this though, so I think it should be done. Will try to prioritize in the coming month.

Agree with George that StableHLO repo is the proper place for this issue. Closing this one as such, will use the linked issue above to track.

**Comment by eedalong** [comment]
Great, Thx!
