### ISSUE TITLE
Minimum C++ std requirement for xla?

### ISSUE THREAD

**Issue by ipcamit** [openxla/xla#8463]
I am trying to follow the docker-cpu instructions from here: https://github.com/openxla/xla/blob/main/docs/developer_guide.md

However when I try and compile xla as
```
bazel build --test_output=all --spawn_strategy=sandboxed //xla/...
```

I keep getting following compilation error:
```
xla/service/gpu/stream_executor_util_test.cc:35:8: error: defaulted 'bool xla::gpu::{anonymous}::Result::operator==(const xla::gpu::{anonymous}::Result&) const' only available with '-std=c++20' or '-std=gnu++20'
   35 |   bool operator==(const Result& other) const = default;
      |        ^~~~~~~~
INFO: Elapsed time: 42.630s, Critical Path: 20.20s
INFO: 67 processes: 41 internal, 26 processwrapper-sandbox.
FAILED: Build did NOT complete successfully
```

Do we need minimum C++20 support? If yes how to enable it in bazel options? Also why does it need `xla::gpu` module? I explicitly tried to disable GPUs.

Thank you

**Comment by dimitar-asenov** [comment]
Thanks for flagging this. I just pushed a fix to adjust that code to work with C++17:
https://github.com/openxla/xla/commit/de7c1527d817948929a8615ea7483c83380b02bc
