### ISSUE TITLE
[BUG] Inconsistent compiled JAX running results on CPU

### ISSUE THREAD

**Issue by Randl** [openxla/xla#8471]
I'm encountering a bug that I think is related to HLO execution.

When I run the JAX code, the code randomly fails from time to time; all the seeds are fixed. Moreover, I verified that the compiled HLO code is identical, which is why I suspect the problem is in execution.

Here is MWE
https://github.com/Randl/lineax_bug_mwe
it is ~350 lines long. Running `runt2.sh` will run the test 200 times, which locally always results in at least one fail.

Unfortunately, I'm not proficient with XLA; I've tried to run generated HLO ([fn_hlo.txt](https://github.com/openxla/xla/files/13932438/fn_hlo.txt)) following the [example](https://github.com/google/jax/tree/main/examples/jax_cpp), but it appears to be outdated and crashes even after I fixed some errors.

I've earlier reported this to JAX (https://github.com/google/jax/issues/18904), but I now think it is not a JAX bug.

**Comment by patrick-kidger** [comment]
Incidentally, is there any documentation on how to run HLO as an end user? I believe there is a HLO-consuming compiler/interpreter somewhere (?)

It'd be nice to simply bisect through the HLO to find the problematic op.

FWIW I've been able to reproduce this: on CPU and Ubuntu, the program returns correct results about 98% of the time, and an incorrect result (always the same incorrect result, at least for me) the other 2% of the time.

**Comment by patrick-kidger** [comment]
Also, @Randl, can you specify the inputs to the HLO somewhere? That'd make just the HLO and those inputs form a standalone MWE.

**Comment by Randl** [comment]
Yep, the inputs are
`[ 0.22919082-0.29173374j -0.47856281-0.15508787j -0.74544327+0.35617767j]`

**Comment by Randl** [comment]
I've tried to use `hlo_bisect` to bisect the bug 
https://github.com/openxla/xla/blob/5ea80986813c3eef73c4d53ee881c203839f2c16/xla/tools/hlo_bisect/hlo_bisect.cc#L27-L39
However, it looks like neither text nor binary exported from jax can be read by XLA?
For text I get 
```
2024-02-05 12:23:40.660789: F ./xla/shape.h:201] Check failed: has_layout() element_type: C128 dimensions: 3 is_dynamic_dimension: false
```
and for binary proto (exported with `as_serialized_hlo_module_proto` I get
```
Can't parse /home/evgeny/general_code/xla/fn_hlo.proto as binary proto
```

**Comment by patrick-kidger** [comment]
Tagging @mattjj as the fallback person to tag on JAX issues when I'm not sure how else to direct this!

We're getting nondeterministic compilation from the same HLO; specifically ~2% of compilations will produce a program that returns the wrong result.

**Comment by Randl** [comment]
With help of @akuegel I was able to run the HLO: [current version with embedded inputs](https://github.com/openxla/xla/files/14180351/fn_hlo.txt). However I didn't see a single fail over 400+ runs. So maybe the bug is somewhere in Jax interfacing with XLA?

**Comment by Randl** [comment]
Alternatively maybe its some internal state that is kept constant when I'm running multiple times in same executable, I'll try to run externally

**Comment by Randl** [comment]
I've managed to reduce the MWE to the following:
```
ENTRY main {
  tmp_0 = c128[3]{0} constant({(0.22919082088459086, -0.2917337444013578), (-0.47856281280306368, -0.15508787412511868), (-0.745443272523875, 0.35617767151516477)}), sharding={replicated}
  tmp_1 = c128[3]{0} fusion(c128[3]{0} tmp_0), kind=kLoop, calls=
  {
    tmp_0 = c128[3]{0} parameter(0)
    tmp_1 = f64[3]{0} real(c128[3]{0} tmp_0)
    tmp_2 = f64[3]{0} imag(c128[3]{0} tmp_0)
    tmp_3 = f64[3]{0} negate(f64[3]{0} tmp_2)
    ROOT tmp_4 = c128[3]{0} complex(f64[3]{0} tmp_1, f64[3]{0} tmp_3)
  }
  tmp_2 = c128[3,3]{0,1} constant({ { (-3.4683985041370184, 0.2818515524340488), (-2.0531999581789173, 0.76532647668268594), (5.269823805569831, 3.5613196166646359) }, { (-2.559036532612764, -0.3698252257987209), (-0.25420681272147494, -1.8022993744788929), (1.667097371428415, 2.7456472301998929) }, { (1.3575242846983384, -4.1063133419096447), (1.4836047923312523, -1.9767224256595632), (-6.86256834124183, -0.81498779940376331) } })
  tmp_3 = c128[3]{0} dot(c128[3]{0} tmp_1, c128[3,3]{0,1} tmp_2), lhs_contracting_dims={0}, rhs_contracting_dims={0}
  tmp_4 = c128[3,3]{0,1} constant({ { (-0.35961650795202704, -0.3574244167201307), (0.16636708257665359, 0.13263255633488857), (1.27318783450939, 0.88189620886301057) }, { (0.35700332955161357, 0.18796015296329902), (-0.837553199539162, -0.78027940540578256), (0.20127147836679504, 0.60223804844342244) }, { (0.58774655732207071, 0.46419954874803704), (0.094338355650602168, -0.28282809935266839), (0.73162017785689926, -0.0642288464334354) } })
  tmp_5 = c128[3]{0} dot(c128[3]{0} tmp_1, c128[3,3]{0,1} tmp_4), lhs_contracting_dims={0}, rhs_contracting_dims={0}
  tmp_6 = c128[3]{0} fusion(c128[3]{0} tmp_3, c128[3]{0} tmp_5), kind=kLoop, calls=
  {
    tmp_0 = c128[3]{0} parameter(1)
    tmp_1 = c128[3]{0} constant({(1.8662642516361887, -1.0711323052056121), (0.26333651876420233, -2.397191531077155), (-1.1171098790664813, 1.0158783792828929)})
    tmp_2 = c128[3]{0} multiply(c128[3]{0} tmp_0, c128[3]{0} tmp_1)
    tmp_3 = c128[3]{0} parameter(0)
    ROOT tmp_4 = c128[3]{0} add(c128[3]{0} tmp_2, c128[3]{0} tmp_3)
  }
  tmp_7 = c128[3]{0} fusion(c128[3]{0} tmp_6), kind=kLoop, calls=
  {
    tmp_0 = c128[3]{0} parameter(0)
    tmp_1 = f64[3]{0} real(c128[3]{0} tmp_0)
    tmp_2 = f64[3]{0} imag(c128[3]{0} tmp_0)
    tmp_3 = f64[3]{0} negate(f64[3]{0} tmp_2)
    ROOT tmp_4 = c128[3]{0} complex(f64[3]{0} tmp_1, f64[3]{0} tmp_3)
  }
  tmp_8 = c128[3]{0} copy(c128[3]{0} tmp_7)
  tmp_9 = c128[3]{0} copy(c128[3]{0} tmp_8)
  tmp_10 = c128[] dot(c128[3]{0} tmp_6, c128[3]{0} tmp_7), lhs_contracting_dims={0}, rhs_contracting_dims={0}
  tmp_11 = c128[] copy(c128[] tmp_10)
  tmp_12 = c128[3,3]{1,0} constant({ { (-3.4683985041370184, 0.2818515524340488), (-2.0531999581789173, 0.76532647668268594), (5.269823805569831, 3.5613196166646359) }, { (-2.559036532612764, -0.3698252257987209), (-0.25420681272147494, -1.8022993744788929), (1.667097371428415, 2.7456472301998929) }, { (1.3575242846983384, -4.1063133419096447), (1.4836047923312523, -1.9767224256595632), (-6.86256834124183, -0.81498779940376331) } })
  tmp_13 = c128[3]{0} dot(c128[3,3]{1,0} tmp_12, c128[3]{0} tmp_9), lhs_contracting_dims={1}, rhs_contracting_dims={0}
  tmp_14 = c128[3,3]{1,0} constant({ { (-0.35961650795202704, -0.3574244167201307), (0.16636708257665359, 0.13263255633488857), (1.27318783450939, 0.88189620886301057) }, { (0.35700332955161357, 0.18796015296329902), (-0.837553199539162, -0.78027940540578256), (0.20127147836679504, 0.60223804844342244) }, { (0.58774655732207071, 0.46419954874803704), (0.094338355650602168, -0.28282809935266839), (0.73162017785689926, -0.0642288464334354) } })
  tmp_15 = c128[3]{0} constant({(1.8662642516361887, -1.0711323052056121), (0.26333651876420233, -2.397191531077155), (-1.1171098790664813, 1.0158783792828929)})
  tmp_16 = c128[3]{0} multiply(c128[3]{0} tmp_9, c128[3]{0} tmp_15)
  ROOT tmp_17 = c128[3]{0} dot(c128[3,3]{1,0} tmp_14, c128[3]{0} tmp_16), lhs_contracting_dims={1}, rhs_contracting_dims={0}
}
```
When running with 
```
for i in {1..500}
do
  TEST_TMPDIR=/home/evgeny/general_code/xlaouts/tmp bazel run --config=dbg -- //xla/tools:run_hlo_module --input_format=hlo --run_test_hlo_passes=false --run_reference_hlo_passes=false --platform=cpu --random_init_input_literals=true /home/evgeny/general_code/xla/fn_hlo.txt  2> /home/evgeny/general_code/xlaouts/out$i.log
done
```
I get the following output
```
Expected literal:
c128[3] {(-5.9966834010646419, 11.07832785025858), (-5.7960808995850908, 0.43276741701963484), (-6.0352414946810624, 5.3437110623738393)}

Actual literal:
c128[3] {(-1.9073419756365961, 6.1298637395994264), (3.4381439319157021, 0.61186491262545639), (-14.240208282931523, 3.0580929877567735)}
1/1 runs miscompared.
```
Specifically, it failed 3/500 times for this run.

**Comment by mooskagh** [comment]
What seems to happen there is `tmp_4` and `tmp_14` constants are the same, except thay have different layout (`{0,1}` vs `{1,0}`), but they are still being deduplicated, which results in `tmp_16` using transposed matrix for multiplication.

**Comment by Randl** [comment]
@mooskagh I think you're right. Specifically, when I changed one number in `tmp_14`, the were no fails out of 1000+ runs.

Do you have any idea why it happens?

**Comment by patrick-kidger** [comment]
Awesome. I'm really glad we got to the bottom of this one -- thank you for the fix!
